- pysat/_instrument.py
allow units_label and name_label to be passed into instrument instantiation
> Units Label and Name Label at Instantiation

- CHANGELOG.md
- docs/supported_instruments.rst
- pysat/instruments/__init__.py
- pysat/instruments/icon_euv.py
- pysat/tests/test_icon_ivm.py
- pysat/tests/test_instruments.py
Added experimental support for ICON EUV level-2 data. The preamble on variable names is automatically removed for brevity. Unit tests are included. A note was added to the change log. The instrument was added to the documentation.
> ICON EUV Initial Support

- CHANGELOG.md
- pysat/_instrument.py
- pysat/instruments/pysat_testing.py
- pysat/instruments/pysat_testing2d.py
- pysat/tests/test_avg.py
- pysat/tests/test_utils.py
- pysat/utils.py
Additional testing for seasonal averages for multiple data types and distributions.
> Additional Unit Tests

- pysat/instruments/icon_euv.py
> ICON EUV Update

- pysat/_instrument.py
Modify strftime to use %m/%d/%Y instead of %D (not available on all
platforms)
> Fix platform dependent strftime

- pysat/_custom.py
- pysat/_files.py
- pysat/_instrument.py
- pysat/_meta.py
- pysat/_orbits.py
- pysat/tests/test_meta.py
- pysat/utils.py
Updated the .py files in the main pysat directory.  Changes include:
- removing trailing whitespace
- Splitting up most of the lines that spanned too many characters
- Adding docstrings when missing
> PEP8 updates

- docs/new_instrument.rst
- docs/supported_instruments.rst
- pysat/instruments/__init__.py
- pysat/instruments/cnofs_ivm.py
- pysat/instruments/cnofs_plp.py
- pysat/instruments/cnofs_vefi.py
- pysat/instruments/dmsp_ivm.py
- pysat/instruments/iss_fpmu.py
- pysat/instruments/nasa_cdaweb_methods.py
- pysat/instruments/rocsat1_ivm.py
- pysat/instruments/timed_see.py
- pysat/tests/test_instruments.py
- setup.py
Added DMSP_IVM support. Improved output from test_instruments. CDAWebmethods updated to support both sat_id and tag. Documentation updated.
> DMSP IVM support via Madrigal

- pysat/instruments/demeter_iap.py
- pysat/instruments/demeter_methods.py
Updated download routine, variable names, PEP8 compliance, and added coordinate conversion routines.
> DEMETER updates

- .gitignore
- pysat/_files.py
It is updated to fix the future warning about the get_duplicates() function. This function is deprecated and will be removed in a future release.
> fixed the get_duplicates future warning

- docs/supported_instruments.rst
- pysat/_instrument.py
- pysat/instruments/dmsp_ivm.py
- pysat/instruments/jro_isr.py
- pysat/instruments/madrigal_methods.py
- pysat/instruments/template_instrument.py
Added Jicamarca ISR data, as well as a methods routine for all Madrigal data files.
> Jicamarca ISR

- .github/pull_request_template.md
- CONTRIBUTING.md
Updated documentation as part of issue #102
> Add pull request template

- pysat/instruments/jro_isr.py
- pysat/instruments/madrigal_methods.py
- pysat/model_utils.py
- pysat/utils.py
Fixed time bug, added location routines, and added xarray Madrigal support.
> Jro isr update

- README.md
- pysat/__init__.py
- pysat/constellations/__init__.py
- pysat/instruments/__init__.py
- pysat/model_utils.py
- pysat/ssnl/__init__.py
- pysat/utils.py
Added docstrings to address issue #100.
check:
import pysat
help(pysat)
help(pysat.utils)
help(pysat.model_utils)
help(pysat.instruments)
help(pysat.ssnl)
support added for constellations as well, though this doesn't currently load automatically.,
> Add documentation

- .travis.yml
- docs/supported_instruments.rst
- pysat/instruments/jro_isr.py
- pysat/instruments/madrigal_methods.py
Downselects loaded jro data to correspond with supplied date.
> Fix for issue #121

- .travis.yml
- docs/conf.py
- docs/supported_instruments.rst
- pysat/_files.py
- pysat/_instrument.py
- pysat/instruments/cnofs_ivm.py
- pysat/instruments/cnofs_plp.py
- pysat/instruments/cnofs_vefi.py
- pysat/instruments/demeter_iap.py
- pysat/instruments/demeter_methods.py
- pysat/instruments/dmsp_ivm.py
- pysat/instruments/iss_fpmu.py
- pysat/instruments/jro_isr.py
- pysat/instruments/madrigal_methods.py
- pysat/instruments/nasa_cdaweb_methods.py
- pysat/instruments/rocsat1_ivm.py
- pysat/instruments/superdarn_grdex.py
- pysat/instruments/supermag_magnetometer.py
- pysat/instruments/template_cdaweb_instrument.py
- pysat/instruments/template_instrument.py
- pysat/instruments/timed_see.py
- setup.py
Heads up pull request that the files upgrade has begun. I've broken up the from_os class method into multiple methods that will be used to support parsing of remote filenames.
Pull started now to attach to the project.
> Files upgrade

- pysat/instruments/jro_isr.py
- pysat/model_utils.py
- pysat/tests/test_utils.py
- pysat/utils.py
Some testing updates and bugfixes to routines recently added as a part of the Models project
> Model project update with bugfixes

- pysat/instruments/.#sw_f107.py
- pysat/instruments/__init__.py
- pysat/instruments/sw_f107.py
- pysat/instruments/sw_kp.py
- pysat/instruments/sw_methods.py
- pysat/model_utils.py
- pysat/tests/test_instruments.py
- pysat/tests/test_sw.py
- pysat/tests/test_utils.py
- pysat/utils.py
Added merging routines to allow people to combine measured and forecasted Kp and F10.7 indexes into a single instrument object.  Measured values are given priority over forecasted values.
Builds off of pull request #138, which should be merged first.
> SW merging

- pysat/instruments/sw_f107.py
Changed prelim download to always update any file whose range spans today, if that date range is specified when downloading data.  This will ensure that this file is updated.
Addresses issue #161
> Update download procedure for prelim F10.7 data

- pysat/ssnl/occur_prob.py
- pysat/tests/test_ssnl_occur_prob.py
Addresses #51.
Summary of changes:
- Unit tests added for `ssnl.occur_prob`
- Bugs in 3D routines fixed
- PEP8 / style
> Testing for occur_prob.py

- pysat/instruments/demeter_iap.py
- pysat/instruments/dmsp_ivm.py
Fixed bug where no cleaning removed all data instead of returning all data.
> Dmsp clean bugfix

- pysat/_files.py
- pysat/_instrument.py
- pysat/_orbits.py
- pysat/instruments/cosmic_gps.py
- pysat/model_utils.py
- pysat/tests/test_ftp_instruments.py
- pysat/tests/test_icon_ivm.py
- pysat/tests/test_instruments.py
- pysat/tests/test_omni_hro.py
- pysat/tests/test_orbits.py
- pysat/tests/test_ssnl_ave.py
- pysat/tests/test_ssnl_occur_prob.py
- pysat/tests/test_ssnl_plot.py
- pysat/tests/test_utils.py
- pysat/tests/test_utils_stats.py
- pysat/tests/test_utils_time.py
- pysat/utils/time.py
Scrubbed the code using pyflakes to identify unused lines of code.
> pyflakes cleanup

- .travis.yml
- pysat/_instrument.py
- pysat/_orbits.py
Addresses #207.
Summary of changes:
- Updates Travis CI testing to use python 3.7 in the xenial environment
- Fixed a bug in python 3.7 caused by change in behvaiour of StopIteration (#207)
- Cleaned up unused imports and commented code.
- pep8 style adjustments
> Python 3.7 testing and compatibility

- pysat/ssnl/plot.py
- pysat/tests/test_ssnl_plot.py
Addresses bug in #193.
Bug was caused by indentation errors. Non-existent limits were applied to the second axis, breaking the plot. 
Also updated routine to check for interactive plot settings before turning this feature off and on. Added unit test for this as well.
> Fix for 193

- setup.py
Added minimum support for pandas to address #219.
Also updated setup info to include python 3.7.
> bugfix for #219

- pysat/_files.py
- pysat/_instrument.py
- pysat/_orbits.py
Addresses #225.
Updates try-except statements that issue custom error messages to save the default error message and append the custom message.  Based on discussion in #208.
> Error handling

- pysat/_files.py
- pysat/instruments/methods/nasa_cdaweb.py
Addresses #200.
This has been fixed for a while in the maven_ngims branch.  Full implementation there is dependent on other file issues (non-unique datetimes in timeseries) in ngims, which may take a while to sort out.  Requesting a pull on this now to make the cdaweb upgrade cleaner and close out issue #200.
> Update to cdaweb list_remote_files

- CHANGELOG.md
- pysat/_instrument.py
- pysat/instruments/dmsp_ivm.py
Updates changelog file for v2.0.0.  
Also fixes a comment bug found in #247.
> Update to Changelog

- CHANGELOG.md
- README.md
- docs/citing.rst
- docs/index.rst
Addresses #278 
Adds a page to documentation with discussion of citations, including sample bibtex info.
No changes to code.
> DOC: Add citation info

- .travis.yml
- CHANGELOG.md
- README.md
- pysat/__init__.py
- setup.py
Addresses #287 and multiple other bugs.  Required to make travis work with the move to pysat organization.
Primary Changes
- `matplotlib` and `netCDF4` added to install_requires
- Badge updates from `rstoneback` to `pysat`
- Code in setup designed for Travis updated to `pysat`
Additional Changes
- Cleaned up multiple imports of `os` in setup
Tested on Travis CI (changes to travis setup)
> BUG: Update travis routines for pysat organization

- CHANGELOG.md
- pysat/_instrument.py
Addresses #259
Updating the instrument docstring to reflect behaviour of bounds.  Includes some whitespace cleanup.
n/a
- [na] I have added tests that prove my fix is effective or that my feature works
> DOC: Update bounds docstring

- CHANGELOG.md
- pysat/_instrument.py
- pysat/_meta.py
- pysat/tests/test_meta.py
Addresses #275 
Fixes case sensitive of keep method
- test_meta.py:TestBasics.test_keep_meta updated
- test_transfer_attributes_to_instrument_no_meta_attr will not pass due to the way attributes will be stored. Not sure when to handle this in terms of release schedule
* Mac OS
* Python 3.7.3 (miniconda)
> Metadata keep

- README.md
The badge on the main page is still pointing to the old organization.
> DOC: Update README.md with badge info

- CHANGELOG.md
- pysat/instruments/cosmic_gps.py
A user reported an inability to load atmPrf files as part of cosmic_gps in issue #333. I have a first draft fix to support loading. I also noticed a couple feedback bugs, which I've corrected.
Downloaded and loaded COSMIC atmPrf files on my local machine.
The user report has a more complete listing (#333)
* Mac OS 10.12.6, also reproduced on newer version
* pysat 2.1
> Cosmic Bugs

- CHANGELOG.md
- pysat/instruments/cosmic_gps.py
Addresses #333, Twin to #334.
Main discussion can occur in #334, but issues unique to 3.0 merge should occur here.
> Cosmic bugs -- pysat 3.0 edition

- CHANGELOG.md
- pysat/instruments/methods/sw.py
- pysat/tests/test_sw.py
Addresses #296 
This follows on from #285 by fixing the same problem with kp in the combine_f107 routine.  This also adds a unit test for the f107 problem.
Tested locally using pytest
Python 3.7.3
Mac 10.14.6
> Bugfix for combine_f107 with no data

- CHANGELOG.md
- pysat/instruments/pysat_testing.py
- pysat/instruments/pysat_testing2d.py
- pysat/instruments/pysat_testing2d_xarray.py
- pysat/instruments/pysat_testing_xarray.py
Addresses #339.  Updates testing instrument documentation to better reflect behaviour of `tag` and `sat_id`.
n/a, changes to docstrings
> pysat_testing docstrings update

- CHANGELOG.md
- pysat/instruments/pysat_testing.py
- pysat/instruments/pysat_testing2d.py
- pysat/instruments/pysat_testing2d_xarray.py
- pysat/instruments/pysat_testing_xarray.py
Addresses # 339.  Twin to #340.
> pysat_testing docstrings -- pysat 3.0.0 edition

- CHANGELOG.md
- pysat/instruments/cnofs_ivm.py
> BUG: SettingWithCopyWarning in `cnofs_ivm` cleaning routine -- pysat 3.0.0 edition

- CHANGELOG.md
- docs/tutorial.rst
- pysat/_constellation.py
- pysat/_custom.py
- pysat/_instrument.py
- pysat/instruments/methods/madrigal.py
- pysat/tests/test_constellation.py
- pysat/tests/test_custom.py
- pysat/tests/test_instrument.py
- pysat/tests/test_orbits.py
Addresses #361 
Renames `custom.add` as `custom.attach`.
pytest locally and on Travis CI.
> API: custom.add renamed as custom.attach

- .travis.yml
- CHANGELOG.md
Addresses #383 
This is a fix for recent changes in the Travis CI environment.  See #382 for more discussion.
- Bug fix - testing environment (non-breaking change which fixes an issue)
via Travis CI
> TST: Update Travis CI environment

- .travis.yml
- CHANGELOG.md
- pysat/instruments/cosmic_gps.py
Addresses # 370
Companion pull to #370 
> Cosmic time bug 3

- CHANGELOG.md
- pysat/tests/test_constellation.py
- pysat/tests/test_utils_coords.py
- pysat/tests/test_utils_time.py
- pysat/utils/coords.py
- pysat/utils/time.py
Addresses ROADMAP
- Removes deprecated functions and associated tests from 3.0 develop branch. 
- Some style updates (whitespace, unused imports)
Travis CI
> Deprecations

- docs/supported_instruments.rst
See #386 - mirror pull for develop3
> Documentation Formatting for Supported Instruments

- .travis.yml
- pysat/instruments/de2_nacs.py
- pysat/instruments/de2_wats.py
Replacement for #405.  Downstream PR of #406.  Twin to #404.
Fixes wrong names in de2 instruments.  Includes Travis environment fixes from #406.
Via Travis CI.
> BUG: DE2 name fixes

- .travis.yml
- CHANGELOG.md
Addresses #403 
Updates testing environment in develop to use conda to manage python environments.  Solves the netcdf issues documented elsewhere without an artifical cap.  Still requires caps for pandas / xarray / kiwisolver.  Should be cleaner to implement while we maintain this branch.
Able to successfully remove Travis caps on pyparsing, beautifulsoup4, cftime, and netCDF4.  Should be easier to maintain.
Change to Travis env, so tested there.
> TST: use conda in Travis CI -- pysat 2.x

- CHANGELOG.md
- pysat/_instrument.py
- pysat/tests/test_instrument.py
> BUG/TST: Fixed display of orbital info in print(inst) / expand unit testing -- pysat 2.2.0

- CHANGELOG.md
- pysat/__init__.py
- pysat/_custom.py
- pysat/_instrument.py
- pysat/_meta.py
- pysat/instruments/methods/general.py
- pysat/tests/instrument_test_class.py
- pysat/tests/test_constellation.py
- pysat/tests/test_files.py
- pysat/tests/test_instrument.py
- pysat/tests/test_meta.py
- pysat/tests/test_methods_general.py
- pysat/tests/test_orbits.py
- pysat/tests/test_registry.py
- pysat/tests/test_utils.py
- pysat/utils/_core.py
- Add more unit tests to check uncovered lines in coveralls
- Automate tests that rely on print statements
- Some restructuring to improve coverage ratings in coveralls
- New tests (non-breaking change which adds functionality)
via Travis CI
> TST: more unit tests and restructure to improve coverage

- CHANGELOG.md
- pysat/_files.py
- pysat/instruments/cosmic_gps.py
- pysat/tests/test_files.py
Addresses #337.  Twin to #439.
See #439.
> BUG: recognize strings in parse delimit -- pysat 3.0.0 edition

- CHANGELOG.md
- pysat/instruments/cosmic_gps.py
The dates associated with cosmic files weren't always correct. 
- Ran science data analysis using > 1 year of cosmic data
Used more than a year of cosmic data to test robustness.
> BUG: Fixed file date association

- CHANGELOG.md
- pysat/instruments/cosmic_gps.py
Date assignment of files for COSMIC was not correct. Develop-3 version of pull #445 
> BUG: Fixed cosmic file date assignment

- CHANGELOG.md
- pysat/_instrument.py
- pysat/_meta.py
- pysat/tests/test_meta.py
Companion to #432 for develop-3
Travis CI
> NetCDF Export NaN metadata for develop-3

- CHANGELOG.md
- README.md
- docs/installation.rst
- setup.py
Addresses #393.
Includes a discussion of how to install via github, as well as a list of requirements and discussion of how to access the develop branches. Also points people to anaconda rather than enthought, as in pysatMissions.
- Documentation update (non-breaking change which fixes an issue)
```
cd docs
make html
```
> DOC: Updates to installation instructions -- pysat 2.2.0

- CHANGELOG.md
- README.md
- docs/installation.rst
Addresses #393.
Twin to #449.  Includes changes specific to develop-3.
See #449
> DOC: Updates to installation instructions -- pysat 3.0.0

- .coveragerc
- pysat/instruments/methods/sw.py
- pysat/instruments/methods/testing.py
- pysat/instruments/templates/template_cdaweb_instrument.py
- pysat/instruments/templates/template_instrument.py
- pysat/tests/test_sw.py
- setup.cfg
Removes the flake8 exceptions for:
- instruments/methods/sw
- instruments/methods/testing
- instruments/templates/template_cdaweb_instrument
- instruments/templates/template_instrument
- tests/test_sw
Scrubs the code for flake8 compliance.
via pytest --flake8
> STY: flake8 -- instrument methods, templates, and test_sw

- pysat/_meta.py
- pysat/_orbits.py
- setup.cfg
Removes the flake8 exceptions for meta and orbits, and updates style throughout.
via pytest.
> STY: flake8 -- meta and orbits

- pysat/tests/test_constellation.py
- pysat/tests/test_custom.py
- pysat/tests/test_meta.py
- pysat/tests/test_orbits.py
- setup.cfg
Removes exceptions and scrubs:
- test_constellation
- test_custom
- test_meta
- test_orbits
Also, found some test instruments that were still using tag='10' instead of sat_id='10' to reduce data size.  Should speed things up a bit.
via pytest
> STY: flake8 -- test files

- CHANGELOG.md
- pysat/_instrument.py
- pysat/instruments/icon_euv.py
- pysat/instruments/icon_fuv.py
- pysat/instruments/icon_ivm.py
- pysat/instruments/icon_mighti.py
- pysat/instruments/pysat_testing.py
Transfers keywords and default values defined for Instrument.load to inst.kwargs.
Tested locally by loading ICON data
> Icon 220 rs

- CHANGELOG.md
- pysat/_instrument.py
- pysat/tests/test_instrument.py
- setup.cfg
- Adds unit tests to cover download functions using the test instruments.  
- Improves some flake8 issues with the _instrument code.
Uses caplog to ensure correct path is taken through the code, since the download for test instruments just returns lists of files.
- test / style fix (non-breaking change which fixes an issue)
via pytest
> TST/STY: improve _instrument.py

- pysat/instruments/pysat_testing2d.py
- pysat/tests/test_instrument.py
This is a start at fixing the test coverage.  Still a couple of tests that don't pass for the 2d xarray objects.
> TST: add 2d instruments to test_instrument

- pysat/instruments/demeter_iap.py
- pysat/instruments/omni_hro.py
- pysat/tests/test_omni_hro.py
- setup.cfg
Removes the flake8 exceptions for:
- instruments/demeter_iap
- instruments/omni_hro
- tests/test_omni_hro
Scrubs the code for flake8 compliance.
Via pytest --flake8
> STY: flake8 -- demeter_iap and omni_hro

- pysat/instruments/sw_dst.py
- pysat/instruments/sw_f107.py
- pysat/instruments/sw_kp.py
- setup.cfg
Removes the flake8 exceptions for:
- instruments/sw_dst
- instruments/sw_f107
- instruments/sw_kp
Scrubs the code for flake8 compliance.
Via pytest --flake8
> STY: flake8 -- sw instruments

- pysat/tests/test_utils_time.py
- setup.cfg
Updates the test_utils_time file to use a class structure with setup and teardown where appropriate.  Also removes the flake8 exceptions and scrubs code.
locally via pytest --flake8
> STY: test_utils_time -- flake8 and use class structure

- CHANGELOG.md
- pysat/instruments/rocsat1_ivm.py
Addresses #500 
Updates path for move of rocsat / formosat data.
```
import logging
import pysat
pysat.logger.setLevel(logging.INFO)
ivm = pysat.Instrument('rocsat1','ivm')       
date = dt.datetime(2002,1,1) 
ivm.download(date, date)
```
* Mac OS X 10.15.4
* Python 3.7.3
> MAINT: update rocsat / formosat data path

- pysat/tests/test_utils.py
- pysat/utils/_core.py
- pysat/utils/time.py
- setup.cfg
Removes the flake8 exceptions for 
- utils._core
- utils.time
- tests.test_utils
via pytest --flake8
> STY: flake8 -- utils and tests

- pysat/_instrument.py
- pysat/tests/test_instrument.py
- setup.cfg
- Removes the exceptions for _instrument.py
- renames several local variables to get under the 80 character limit
- Added fix for #504 and new unit test 
via pytest --flake8
> STY: flake8 -- instrument.py

- demo/cnofs_vefi_dc_b_orbit_plots.py
- pysat/tests/test_instrument.py
- setup.cfg
This is the last of the major flake8 scrubs for the code.  The remaining exceptions are the `init` files, which we can discuss later, and several instruments requiring a rewrite after migration to bring them up to date.  The flake8 checks are now fully implemented for the core code.
via pytest --flake
> STY: flake8 scrub -- test_instrument and demos

- .zenodo.json
- CHANGELOG.md
- CONTRIBUTING.md
Added a zenodo json file with creators, access right, and resource type specified.
Partially addresses #495 
It hasn't not sure how to do so.
* Version number
> ENH: added a zenodo json

- CHANGELOG.md
- pysat/_custom.py
- pysat/_files.py
- pysat/_instrument.py
- pysat/tests/test_custom.py
- pysat/tests/test_files.py
- pysat/tests/test_instrument.py
Improves Class object representation for Instrument, Files, and Custom.
Addresses #465
Load a pysat Instrument object and try `print(inst)` and just `inst`.  Also, try `print(inst.files)` and `print(inst.custom)` (with and without print statements).  See the lovely object summaries!
> Instrument, Files, and Custom representation

- .github/pull_request_template.md
- .travis.yml
- CHANGELOG.md
- MANIFEST.in
- pysat/_meta.py
- pysat/instruments/methods/general.py
- requirements.txt
- test_requirements.txt
Updated travis to include separate doc testing and updated PR template to improve release pull requests.
Addresses #495 
This needs to be tested by running on Travis
* Version number
> Travis docs

- CHANGELOG.md
- CONTRIBUTING.md
- docs/requirements.txt
A short style guide for new pysat developers!
Addresses #561 and #493 
This has been tested by me reading it.  Before it can be merged it requires:
> DOCS: Developer style guidelines

- pysat/tests/test_instruments.py
Improves the comments and structure for the setup and teardown functions for the main instrument test class.
Visual inspection
* Operating system: Human Eyes
* Version number: 1.0
* Any details about your local setup that are relevant: Brain sometimes interprets grammar in an odd fashion
> DOC: update comments for instrument tests

- CHANGELOG.md
- pysat/instruments/templates/template_instrument.py
Addresses #538 
Updates the main template with 
- info on testing options
- required functions at the top
Visual inspection of comments
> DOC: Instrument Template update

- CHANGELOG.md
- pysat/_instrument.py
- pysat/_orbits.py
- pysat/tests/test_instrument.py
Updated Instrument object by:
- Adding missing docstrings
- Fixing methods to have the stated behaviour
- Clarifying inline comments
- Organised Instrument class methods and properties by type
- Simplifies some more complex logic statements
Partially Addresses #578 
Running unit tests locally and on Travis CI
> Instrument organisation

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- docs/faq.rst
- requirements.txt
- setup.cfg
- setup.py
- test_requirements.txt
Addresses ROADMAP, #601 
- Moves the setup metadata to setup.cfg
- Reorganized the requirements.txt and test_requirements.txt files to reduce duplication elsewhere
- Update links in community docs
- Updates travis links on readme
requirements.txt now used for pysat requirements, test_requirements.txt now used for all testing related requirements.  All testing requirements installed through pip since some of them not supported by conda.
- Testing fix (non-breaking change which fixes an issue)
Running `python setup.py develop`
Changes to Travis config.  Testing there.
> STY: Streamline setup

- CHANGELOG.md
- docs/new_instrument.rst
- pysat/_instrument.py
- pysat/instruments/pysat_testing.py
- pysat/instruments/pysat_testing2d.py
- pysat/instruments/pysat_testing2d_xarray.py
- pysat/instruments/pysat_testing_xarray.py
- pysat/instruments/templates/template_instrument.py
Changed name of Instrument method `default` to `preprocess`.  Addresses #581.
Ran unit tests locally.
-  [x] pysatSpaceWeather: N/A
> Default2preprocess

- pysat/tests/instrument_test_class.py
Addresses #627 
Keeps unit tests from modifying a user's setup when running locally.
to be added
> TST: use update_files for instrument

- CHANGELOG.md
- pysat/instruments/methods/general.py
- pysat/tests/test_methods_general.py
Improves support for monthly/annual/weekly files by changing `list_files` kwarg to be adaptive instead of a boolean.  Addresses #536 
Added new unit test for evaluation routine, ran tests locally, and ran in conjunction with pysatNASA PR https://github.com/pysat/pysatNASA/pull/28
> Adaptive long time support

- CHANGELOG.md
- CONTRIBUTING.md
- docs/api.rst
- pysat/_meta.py
- pysat/tests/test_meta.py
- pysat/tests/test_utils_testing.py
- pysat/utils/__init__.py
- pysat/utils/testing.py
Created testing utility routines to reduce code duplication throughout pysat and have more informative testing error messages.
Addresses #543 and partially addresses #565.
- Ensuring existing unit tests behave identically with the new test code
- Adding unit tests for the new routines
> New testing utilities applied to `Meta.__eq__`

- CHANGELOG.md
- pysat/__init__.py
- pysat/_files.py
- pysat/_instrument.py
- pysat/_params.py
- pysat/tests/test_constellation.py
- pysat/tests/test_custom.py
- pysat/tests/test_files.py
- pysat/tests/test_instrument.py
- pysat/tests/test_instruments.py
- pysat/tests/test_utils.py
- pysat/utils/_core.py
- pysat/utils/files.py
- pysat/utils/registry.py
- pysat/utils/time.py
> Pysat params with files

- pysat/_files.py
Code scrub of Files class.  Includes:
- Adding and improving docstrings
- Changing variable names to be descriptive
- Organizing class methods by type
- Adding and clarifying block/inline comments
- Style update
Running unit tests locally.
> File style update

- pysat/_instrument.py
- pysat/_orbits.py
- pysat/tests/test_orbits.py
Style update for the Orbits class!
- Update to standards
Ran unit tests locally
- [N/A] I have added tests that prove my fix is effective or that my feature works
> Orbit style update

- requirements.txt
- setup.cfg
Fixes issue with setup configuration identified in https://github.com/pysat/pysatSpaceWeather/pull/36
Ran setup locally
- [N/A] Add a note to ``CHANGELOG.md``, summarizing the changes
> Requirements update

- CHANGELOG.md
- pysat/_instrument.py
Removed `labels` attribute, as it is not needed anymore.  This addresses #483 
Ran unit tests locally
> Remove unnecessary attribute in Instrument

- .zenodo.json
- docs/citing.rst
- docs/installation.rst
- docs/tutorial_iteration.rst
Addresses #617 
Folds in some documentation changes from the v2.2.2 release. Plus includes a fix for the zenodo.json.
I don't currently know how to test the .json without a release.
> V222 redirect

- docs/api.rst
- pysat/instruments/templates/template_instrument.py
- pysat/utils/files.py
- pysat/utils/registry.py
Some doc fixes that should go into @jklenzing's larger branch.
Addresses #649 
Running `make doctest`
* Version number: Python 3.7
- [N/A] Make sure you are merging into the ``develop`` (not ``main``) branch
- [N/A] Add a note to ``CHANGELOG.md``, summarizing the changes
> Some doc warning removal

- .zenodo.json
Added references and keywords to zenodo json.  Addresses #646 
Ran through a json linter.
> ENH: added references, keywords to zenodo

- CHANGELOG.md
- docs/api.rst
- docs/new_instrument.rst
- pysat/_instrument.py
Updated the new_instrument documentation to be pysat 3.0 compliant and include descriptions of all missing optional attributes.  While doing this, I discovered that the treatment of `directory_format` was unnecessarily restrictive, so I changed it.
Addresses #512 and partially addresses #528.
This has been tested by creating the docs locally and also running the instrument unit tests.
> DOCS: New Instrument update

- docs/dependency.rst
- docs/installation.rst
- docs/instruments/testing_instruments.rst
Updated the installation-related pages, removing pysat 2 related text and using real section headers.  Partially Addresses #528.
Ran `/opt/local/bin/sphinx-build-3.7 -b linkcheck docs dist/docs`
> Docs: install update

- pysat/_instrument.py
Addresses #660 
updates docstring standards
Visual inspection
> DOC: remove ', optional'

- docs/api.rst
- docs/citing.rst
- docs/new_instrument.rst
- pysat/utils/_core.py
- pysat/utils/coords.py
- pysat/utils/registry.py
- pysat/utils/testing.py
- pysat/utils/time.py
Update to the documentation API and citation guideline sections.  Partially addresses #528.
Creating the docs locally and testing the links to the relevant documentation.
> DOC: API and citing update

- docs/tutorial/tutorial_v3_upgrade.rst
- pysat/__init__.py
- pysat/tests/test_instrument.py
- pysat/tests/test_utils.py
- pysat/utils/__init__.py
- pysat/utils/_core.py
Addresses # https://github.com/pysat/pysat/issues/610
Updated introductory text.
- Documentation Update
Standard unit tests on TravisCI
> ENH: Updated first-run text

- docs/api.rst
- docs/examples.rst
- docs/installation.rst
- docs/introduction.rst
- docs/quickstart.rst
- docs/tutorial.rst
- docs/tutorial/tutorial_parameters.rst
- pysat/_params.py
- pysat/utils/_core.py
Updated the introduction and quick-start guide, bringing them up-to-date with new pysat standards.  Partially addresses issue #528.
Building the docs locally and ensuring no new warnings were raised.
> Docs: updated introduction and quick-start guide

- docs/tutorial/tutorial_iteration.rst
Expand and update the iteration tutorial. Partially addresses #528 
Running the code
> DOC: update iteration tutorial

- docs/tutorial/tutorial_basics.rst
- docs/tutorial/tutorial_iteration.rst
- docs/tutorial/tutorial_load.rst
- docs/tutorial/tutorial_orbit.rst
- pysat/_orbits.py
Update to the Orbits tutorial.  Partially addresses #528 
**Will be tested by** running the example code and compiling docs locally.
* Version number
> DOC: Updated orbit tutorial

- CHANGELOG.md
- pysat/_custom.py
- pysat/tests/test_custom.py
Deprecates the Custom class
Addresses #506 
Added unit tests
> Deprecate Custom

- pysat/tests/test_utils_coords.py
- pysat/utils/coords.py
Fixed another SLT bug for a different type of broadcasting shape.
Ran locally where error was thrown and added more unit tests.
- [N/A] Make sure you are merging into the ``develop`` (not ``main``) branch
> Bug: SLT calc again

- CHANGELOG.md
- pysat/instruments/methods/general.py
- pysat/tests/test_methods_general.py
Deprecated old kwarg and added new kwarg.  The new kwarg currently only supports inputs that ensure the behaviour of the routine does not change if it or the old kwarg are used.  Addresses #685.
Added new unit tests.
> DEP: instruments.general.list_files kwarg update

- .travis.yml
- CHANGELOG.md
- pysat/_instrument.py
- pysat/instruments/methods/nasa_cdaweb.py
- pysat/tests/test_constellation.py
- pysat/tests/test_custom.py
- pysat/tests/test_files.py
- pysat/tests/test_instrument.py
- pysat/tests/test_instruments.py
- pysat/tests/test_meta.py
- pysat/tests/test_methods_cdaweb.py
- pysat/tests/test_methods_general.py
- pysat/tests/test_model_utils.py
- pysat/tests/test_omni_hro.py
- pysat/tests/test_orbits.py
- pysat/tests/test_ssnl_ave.py
- pysat/tests/test_ssnl_occur_prob.py
- pysat/tests/test_ssnl_plot.py
- pysat/tests/test_sw.py
- pysat/tests/test_utils.py
- pysat/tests/test_utils_coords.py
- pysat/tests/test_utils_stats.py
- pysat/tests/test_utils_time.py
Found warnings about open files in the TravisCI testing log when reviewing pull #722 
TravisCI
> BUG: Open file fix cdaweb

- CHANGELOG.md
- pysat/instruments/champ_star.py
- pysat/instruments/demeter_iap.py
- pysat/instruments/methods/demeter.py
- pysat/instruments/superdarn_grdex.py
- pysat/instruments/supermag_magnetometer.py
- pysat/tests/test_instruments.py
Partially addresses #697 by adding deprecation warnings to all Instrument modules and methods associated with the pysatIncubator package.
Added unit tests for all currently tested routines.
> DEP: pysatIncubator instrument deprecation

- CHANGELOG.md
- pysat/instruments/methods/testing.py
- pysat/ssnl/_core.py
- pysat/ssnl/avg.py
- pysat/ssnl/occur_prob.py
- pysat/ssnl/plot.py
- pysat/tests/test_instrument.py
- pysat/tests/test_instruments.py
- pysat/tests/test_ssnl_ave.py
- pysat/tests/test_ssnl_occur_prob.py
- pysat/tests/test_ssnl_plot.py
Added depreciation warnings, addressing #696.  Added new testing method.
Added new unit tests
> DEP: remaining ssnl routines

- CHANGELOG.md
- pysat/_constellation.py
- pysat/constellations/de2.py
- pysat/constellations/icon.py
- pysat/instruments/cnofs_ivm.py
- pysat/instruments/cnofs_plp.py
- pysat/instruments/cnofs_vefi.py
- pysat/instruments/de2_lang.py
- pysat/instruments/de2_nacs.py
- pysat/instruments/de2_rpa.py
- pysat/instruments/de2_wats.py
- pysat/instruments/icon_euv.py
- pysat/instruments/icon_fuv.py
- pysat/instruments/icon_ivm.py
- pysat/instruments/icon_mighti.py
- pysat/instruments/iss_fpmu.py
- pysat/instruments/methods/icon.py
- pysat/instruments/methods/nasa_cdaweb.py
- pysat/instruments/omni_hro.py
- pysat/instruments/rocsat1_ivm.py
- pysat/instruments/sport_ivm.py
- pysat/instruments/timed_saber.py
- pysat/instruments/timed_see.py
- pysat/tests/test_constellation.py
- pysat/tests/test_instruments.py
- pysat/tests/test_methods_icon.py
Partially addresses #697 by adding deprecation warnings to all Instrument modules and methods associated with the pysatNASA package.
Added unit tests for all currently tested routines.
- [ n/a] My changes generate no new warnings
> DEP: pysatNASA instruments

- pysat/instruments/methods/testing.py
Added a deprecation testing function to pysat 3.0.0 that was created in pysat 2.3.0 to reduce duplicate code.
CI and local tests in `develop` branch.
- [N/A] Make sure you are merging into the ``develop`` (not ``main``) branch
- [N/A] Add a note to ``CHANGELOG.md``, summarizing the changes
> MAINT: added testing function from v2.3.0

- .zenodo.json
- CHANGELOG.md
- docs/conf.py
- docs/new_instrument.rst
- setup.cfg
Addresses #774 
- Improves maintainability of conf.py
- Updates style in conf.py to be flake8 compliant, add checks
- fixed a bug in the links
Inspection via read the docs
* Operating system: RTD
* Version number: ???
*  🐠 😼 🍣 
> STY: conf.py updates

- CHANGELOG.md
- pysat/_instrument.py
Addresses #761
The current structure of data access is not particularly helpful when data access is a problem, since the `try` / `except` construct ignores the first error if data is not accessible.  This catches both error messages and appends them to a custom error if something has gone wrong to aid in debugging.
Assuming registration of pysatSpaceWeather and downlaod of data:
```
import pysat
sw = pysat.Instrument('sw', 'f107', tag='all')
sw.load(2012, 1)
sw[dt.datetime(2012, 1, 1), 'f107']
```
If using the pysatSW 0.0.4 release candidate, use `tag='historic'` instead.  This will still produce an error (this particular date is missing), but now it appends the previous message and adds a suggestion.
``` …
```
> BUG: Data slicing when data does not exist

- CHANGELOG.md
- pysat/__init__.py
- pysat/_constellation.py
- pysat/_instrument.py
- pysat/_params.py
- pysat/constellations/testing.py
- pysat/tests/test_constellation.py
- pysat/tests/test_instrument.py
- pysat/tests/test_utils_time.py
- pysat/utils/time.py
Added constellation methods and attributes needed to make it possible to use the Constellation object in data analysis.
Partially Addresses #764 
Added unit tests.  Also:
```
from pysatSpaceWeather.instruments import ace_mag, ace_swepam
import pandas as pds
half_window = pds.DateOffset(minutes=10)
imf_tag = 'realtime'
imf = pysat._constellation.Constellation(instruments=[pysat.Instrument(inst_module=ace_mag, tag=imf_tag, clean_level='clean', pad=half_window), pysat.Instrument(inst_module=ace_swepam, tag=imf_tag, clean_level='clean', pad=half_window)])
print(imf)
pysat Constellation object:
---------------------------
2 Instruments
Index …
```
> Added useful Constellation attributes

- .github/workflows/main.yml
- set_ga_dir.py
this should allow the deletion of the set_ga_dir script
> Proposed changed for windows testing setup

- CHANGELOG.md
- requirements.txt
- setup.cfg
Addresses #819
Adds pytest as a pysat package requirement
Please describe the tests that you ran to verify your changes. 
- Ran included unit tests
* Operating system: MacOS 10.15.4
* Brand new install of python via conda-forge. See #819 for specific environment creation commands.
> BUG: Added pytest as package requirement

- CHANGELOG.md
- docs/tutorial.rst
- docs/tutorial/tutorial_constellation.rst
- pysat/_constellation.py
- pysat/tests/test_constellation.py
Partially addresses #795 by adding optional kwargs for initializaing a Constellation by specifying lists of platforms, names, tags, and inst_ids.  Also added documentation for this specific functionality, partially addressing #796.
Added a new unit test and an example in the docs.  A further example is given below.  Assumes all modules are registered.
```
import pysat
ivm = pysat.Constellation(names=['ivm'])
print(ivm)
pysat Constellation object:
---------------------------
17 Instruments
Index Platform Name Tag Inst_ID
-------------------------------
0 'cnofs' 'ivm' '' ''
1 'formosat1' 'ivm' '' ''
2 'icon' 'ivm' '' 'a'
3 'icon' 'ivm' '' …
```
> Constellation initialization for registered Instruments

- CHANGELOG.md
- docs/tutorial/tutorial_basics.rst
- pysat/utils/registry.py
Addresses #837 
Adds a simple example for registering instrument support within pysat in tutorial_basics.
- Built documentation locally and inspected visually
* Version number: Python 3.8.3
> DOC: Added simple example for registering instruments within pysat

- CHANGELOG.md
- pysat/_constellation.py
- pysat/_instrument.py
- pysat/tests/test_constellation.py
Addresses #541 by adding a hidden method to set an instrument attribute to the same value across all instruments.  Also improved the Instrument docstrings.
Ran unit tests and added new/missing attributes to the attribute test.
> Added `_set_inst_attr` to Constellation

- CONTRIBUTING.md
- README.md
Updates readme to include location of Slack self-invitation link on GitHub webpage. Also includes a note about development meetings.
- Clink the links in the readme
> STY: Add Slack link

- CHANGELOG.md
- pysat/tests/test_utils_time.py
- pysat/utils/time.py
Partially addresses #565 by:
- combining duplicate unit tests
- adding unit test coverage for additional routines
- adding unit tests for failure conditions
- improving time utility docstrings
Running unit tests locally
> Updates to `pytest.utils.time` unit tests

- CHANGELOG.md
- pysat/tests/test_utils_files.py
- pysat/tests/test_utils_testing.py
- pysat/tests/test_utils_time.py
- pysat/utils/files.py
Partially addresses #565 by improving docstrings and adding additional unit tests for two of the test files.
Adding unit tests and running them locally
* Operating system: OS Mojave
> Update testing and files utilities' unit test style

- CHANGELOG.md
- pysat/instruments/methods/general.py
Addresses #846
Updates usage in example code.  Uses fake instrument name.
Visual inspection
> DOC: docstring examples for list_files

- CHANGELOG.md
- pysat/tests/test_utils.py
- pysat/tests/test_utils_coords.py
- pysat/tests/test_utils_testing.py
- pysat/utils/_core.py
- pysat/utils/coords.py
- pysat/utils/testing.py
Partially addresses #565 by updating the core and coordinate utilities.
Ran unit tests locally
> Update `test_utils` style

- pysat/tests/instrument_test_class.py
- pysat/tests/test_utils.py
- pysat/tests/test_utils_coords.py
- pysat/tests/test_utils_files.py
- pysat/tests/test_utils_testing.py
- pysat/tests/test_utils_time.py
- pysat/utils/__init__.py
- pysat/utils/_core.py
- pysat/utils/coords.py
- pysat/utils/files.py
- pysat/utils/registry.py
- pysat/utils/testing.py
- pysat/utils/time.py
Addresses #857 and #860 (partial)
- Adds unit tests for `pysat.utils.generate_instrument_list`.
- Adjusts class-level definitions of variables in tests
- Docstring scrub:
- instrument_test_class
- utils and submodules
- test_utils and submodules
flake8-docstrings
* flake8, flake8-docstrings
> TST/DOC : Unit tests for `pysat.utils.generate_instrument_list` and docstring scrub for utils area

- .github/workflows/main.yml
- CHANGELOG.md
Updates NEP29 requirements for CI testing.  Implements some style changes in yml.
via github actions.
> TST: update main.yml

- CHANGELOG.md
- docs/tutorial/tutorial_verbosity.rst
Update verbosity tutorial to include some logging gotchas. Addresses #894.
Tested by finding something that didn't work and finding out the way to make it work.
> DOC: update verbosity

- CHANGELOG.md
- pysat/_instrument.py
- pysat/tests/test_instrument.py
Addresses #532
- Added `by_date` kwarg to evaluation functions to improve utility across the unit tests
- Regrouped multiple functions under @pytest.mark.parametrize for testing iteration by date and by file
- Fixed a bug where iteration with step and width is not consistent for date and file iteration
- Combined `verify_exclusive_iteration` and `verify_inclusive_iteration` into `verify_iteration` with `inclusive` boolean kwarg
pytest -vs pysat/tests/test_instrument.py::TestBasics
~~Getting three errors still:~~ Fixed, but leaving comments below for posterity
```
pysat/tests/test_instrument.py::TestBasics::test_iterate_season_frequency_and_width_incl[False-True-values2]
pysat/tests/test_instrument.py::TestBasics::test_iterate_season_freq …
```
> BUG/STY: iteration via date and file, test_instrument consolidation

- CHANGELOG.md
- pysat/_constellation.py
- pysat/tests/test_constellation.py
Addresses #836 by checking the type of all items in the `constellation.instruments` attribute.
- New feature (non-breaking change which adds functionality
Added new unit test
* Operating system: OSX Mojave
> Const inst check

- CHANGELOG.md
- README.md
Updates badge to point at pysat testing results.
Confirmed via inspection the badge now operates as expected.
> Badge update

- CHANGELOG.md
- docs/tutorial/tutorial_custom.rst
- pysat/_constellation.py
- pysat/_instrument.py
- pysat/tests/test_instrument_custom.py
Partially addresses #764 by allowing constellation-level custom functions to be added.
Added new unit tests and an example in the docs.
* Any details about your local setup that are relevant: testing using develop branch of pysatSpaceWeather
> Constellation custom

- pysat/instruments/methods/testing.py
- pysat/instruments/pysat_testing2d.py
- pysat/instruments/pysat_testing_xarray.py
NoneType counts as any.  Fixed using find/replace all.
> STY: any or nonetype

- pysat/_constellation.py
- pysat/_instrument.py
- pysat/tests/classes/cls_instrument_access.py
- pysat/tests/classes/cls_instrument_library.py
- pysat/tests/classes/cls_instrument_property.py
- pysat/tests/test_constellation.py
- pysat/tests/test_files.py
- pysat/tests/test_instrument.py
- pysat/tests/test_instrument_custom.py
- pysat/tests/test_instrument_index.py
- pysat/tests/test_instrument_padding.py
- pysat/tests/test_instruments.py
- pysat/tests/test_meta.py
- pysat/tests/test_methods_general.py
- pysat/tests/test_methods_testing.py
- pysat/tests/test_orbits.py
- pysat/tests/test_utils_coords.py
- pysat/tests/test_utils_files.py
- pysat/tests/test_utils_io.py
Enables `use_header` at Instrument level. Warnings are reduced but there are still over 15k of them. Epoch warning would be next.
- Tweaked `use_header`. Confirmed It works as expected via terminal interaction. …
> Header header

- CHANGELOG.md
- requirements.txt
Addresses #1026
Testing out simple version limit for short term fix for xarray issue.
- xarray Breaking change (fix or feature that would cause existing functionality
- Checking via online test suite
* Operating system: GitHub Actions
> BUG: xarray version limit

- .github/workflows/docs.yml
- .github/workflows/main.yml
- CHANGELOG.md
- docs/dependency.rst
- pysat/tests/classes/cls_ci.py
- pysat/tests/classes/cls_registration.py
- pysat/tests/test_constellation.py
- pysat/tests/test_files.py
- pysat/tests/test_instrument.py
- pysat/tests/test_instrument_custom.py
- pysat/tests/test_instrument_index.py
- pysat/tests/test_instrument_listgen.py
- pysat/tests/test_instrument_padding.py
- pysat/tests/test_instruments.py
- pysat/tests/test_meta.py
- pysat/tests/test_meta_header.py
- pysat/tests/test_meta_labels.py
- pysat/tests/test_methods_general.py
- pysat/tests/test_methods_testing.py
- pysat/tests/test_orbits.py
- pysat/tests/test_params.py
- pysat/tests/test_registry.py
- pysat/tests/test_utils.py
- pysat/tests/test_utils_coords.py
- pysat/tests/test_utils_files.py
- pysat/tests/test_utils_io.py
- pysat/tests/test_utils_testing.py
- pysat/tests/test_utils_time.py
Addresses #1053, #1048
Updates to remove nose syntax.  pytest will remove support for this in the future.
Also updates github actions and NEP29 implementation.
pytest
* Operating system: Mac OS Monterrey
> MAINT: pytest syntax, NEP29, github actions

- CHANGELOG.md
- ecosystem.txt
Now that pysatModels has a versioned release, add it to the counter.
Run a version of this branch. => https://github.com/pysat/pysat/actions/runs/3579281520/jobs/6020317506
* Operating system: Github Actions
> TST: add pysatModels to ecosystem counter

- CHANGELOG.md
- docs/instruments/pysatMadrigal.rst
- docs/instruments/pysatMissions.rst
- docs/instruments/pysatNASA.rst
Addresses #1057
Updates links and style consistency for supported instruments.
Inspecting the docs at readthedocs
> DOC: links to supported instruments

- CHANGELOG.md
- CONTRIBUTING.md
Partially Addresses #816
Updates contributing based on pysatMadrigal
visual inspection
> DOC: update to contributing doc

- CHANGELOG.md
- docs/conf.py
- docs/index.rst
- docs/roadmap.rst
Addresses #845
Copies the roadmap from the wiki page with some format tweaks for rst.
Updates conf.py settings
Inspection of the docs after compile.
> DOC: add roadmap

- CHANGELOG.md
- pysat/utils/files.py
Updated the docstrings and comments in `pysat.utils.files`.  Also changed a ValueError to RuntimeError, to correctly reflect the error type.
Ran unit tests.
> Updated file utility comments and docstrings

- CHANGELOG.md
- docs/tutorial/tutorial_constellation.rst
- pysat/_constellation.py
- pysat/_instrument.py
- pysat/tests/test_constellation.py
- pysat/tests/test_utils_coords.py
- pysat/utils/coords.py
Addresses #764 by adding the last of the targeted methods, `to_inst`, to the Constellation.  Supporting methods/functions were added to Instrument and utils.coords.  Partially addresses #796.
Added an example in the tutorial and a unit test.
> Added Constellation method `to_inst`

- CHANGELOG.md
- docs/tutorial/tutorial_constellation.rst
Addresses #796 by discussing the ways Constellations are the same and different from Instruments.
Ran examples locally.  The DE2 example won't successfully load data, due to https://github.com/pysat/pysatNASA/issues/142
* Any details about your local setup that are relevant `timed_guvi` branch of pysatNASA.
> Constellation example

- CHANGELOG.md
- CONTRIBUTING.md
- docs/devel/pysatEcosystem_Template.rst
- docs/devel/pysatTutorials.rst
- docs/ecosystem.rst
- docs/examples.rst
Addresses #910 by adding links to the pysatEcosystem_Template repository.
Doc tests for links
> DOC: Updated project standards docs

- CHANGELOG.md
- docs/new_instrument.rst
Potentially addresses #793 by updating and revising the new instrument example in the docs.
CI tests.
* Operating system: ReadTheDocs, GitHub Actions
> New Instrument instructions

- .zenodo.json
- CHANGELOG.md
- docs/installation.rst
- docs/tutorial/tutorial_load.rst
Addresses #1121
Updates link redirects. 
Clicking through links. 
* Operating system: Mac
> Update link redirects in docs

- CHANGELOG.md
- docs/tutorial/tutorial_basics.rst
- pysat/_meta.py
- pysat/tests/test_meta.py
Addresses #786 by changing `__setitem__` in Meta to allow direct assignment of metadata.  Also raises an error if the correct assignment type isn't used instead of failing silently.
```
import pysat
inst = pysat.Instrument('pysat', 'testing')
inst.load(date=pysat.instruments.pysat_testing._test_dates[''][''])
inst.meta['mlt', 'notes'] = 'hi, I am a special note!'
print(inst.meta['mlt'])
```
Yeilds:
```
units                                                hours
long_name                              Magnetic Local Time
notes                             hi, I am a special note!
desc         Local time at magnetic field line at equator. …
```
> Update meta `__setitem__`

- CHANGELOG.md
- pysat/_constellation.py
- pysat/_instrument.py
- pysat/tests/classes/cls_instrument_access.py
- pysat/tests/test_constellation.py
Addresses #1078 by adding `drop` and `__delitem__` methods to both the Instrument and Constellation classes.
```
import pysat
from pysat import constellation
inst = pysat.Instrument('pysat', 'testing')
const = pysat.Constellation(const_module=constellations.testing)
inst.load(date=pysat.instruments.pysat_testing._test_dates[''][''])
const.load(date=pysat.instruments.pysat_testing._test_dates[''][''])
del inst['uts']
inst.drop(['mlt', 'slt'])
del const['uts']
const.drop(['mlt_pysat_testing', 'slt_pysat_testing'])
```
If this is a release PR, …
> ENH: added `drop` and `__delitem__` to Instrument and Constellation classes

- README.md
- docs/citing.rst
- docs/introduction.rst
- docs/new_instrument.rst
- docs/tutorial/tutorial_v3_upgrade.rst
Setting this up as a draft for when I catch issues in the docs.
TBD
* Operating system: Hal
* Version number: Python 3.X
> DOC: RC documentation updates

- .github/workflows/main.yml
- .github/workflows/pip_rc_install.yml
- .zenodo.json
- CHANGELOG.md
- pyproject.toml
- pysat/tests/test_instruments.py
- setup.cfg
> pull back changes from RC 3.2.1

- .zenodo.json
- CHANGELOG.md
Addresses #1210
- Updates affiliations for student contributors.
- Updates references in zenodo
via GitHub Actions
> MAINT: zenodo
