pysat/pysat

- pysat/instruments/iss_fpmu.py
Added support for the Floating Potential Measurement Unit (FPMU) on board the International Space Station (ISS) through CDAWeb.  Currently no cleaning routine.
> Added support for ISS FPMU

- CHANGELOG.md
- docs/supported_instruments.rst
- pysat/_files.py
- pysat/_meta.py
- pysat/instruments/__init__.py
- pysat/instruments/icon_ivm.py
- pysat/tests/test_files.py
- pysat/tests/test_instruments.py
Initial upload for NASA ICON Ion Velocity Meter (IVM) support, including basic documentation.
Added support for version and revision numbers in filenames when using the Files.from_os constructor. The most recent version/revision is used when there are conflicting dates. This constructor is used by the generalized support for NASA's CDAWeb.
Added new instruments to the pysat/instruments/__init__
> ICON IVM and Version/Revision Filename Support

- pysat/_meta.py
Updated notes and examples for Meta class to include some info about the base set of metadata attributes tracked by Meta.
Added a note about using these values for programatic access to metadata as well as examples for setting these values.
Added a docstring to the special equal function.
Removed redundant variable use in the hidden attribute setter function.
> Meta docstrings

- pysat/_instrument.py
- pysat/_meta.py
Removed unnecessary function. Improved robustness of meta concat function to ensure consistency between labels across the meta objects.
> Minor Meta cleanup

- pysat/_instrument.py
- pysat/_meta.py
- pysat/instruments/icon_euv.py
- pysat/instruments/icon_ivm.py
- pysat/instruments/pysat_testing2d.py
- pysat/tests/test_meta.py
- pysat/utils.py
Modifies meta to always return a series. If the label corresponds to higher order data, the series will contain the associated meta object in the attribute 'children'.
All meta labels now have first-order keys and may or may not contain children.
> Ho meta fix

- pysat/_instrument.py
- pysat/_meta.py
- pysat/tests/test_instruments.py
- pysat/tests/test_meta.py
Improves robustness when working with higher order data and Meta object.
Improved robustness of higher and lower metadata interactions when setting data via the Instrument object.
Corrected data access for higher order meta object via __getitem_.
Switched some __getitem__ data so that a copy is returned.
Added Meta tests.
Added check to test_instruments to limit testing of loading until a downloaded file is confirmed.
Removed redundant items in Instrument docstring.
> Meta fixes

- docs/supported_instruments.rst
- pysat/_instrument.py
- pysat/instruments/ucar_tiegcm.py
Includes Instrument support for TIEGCM files from UCAR. All variables loaded into .data include 'time' as a dimension. Attributes and other small variables are attached to the Instrument object itself, per pysat design. I should check if that is documented....
I added TIEGCM to the supported instrument documentation.
I modified data setting to give xarray a chance at understanding multidimensional data before I do anything else.
I can't add models label for some reason... perhaps because it isn't my project.
> TIEGCM initial instrument support

- docs/supported_instruments.rst
- pysat/instruments/cnofs_ivm.py
- pysat/instruments/cnofs_plp.py
- pysat/instruments/cnofs_vefi.py
- pysat/instruments/iss_fpmu.py
- pysat/instruments/nasa_cdaweb_methods.py
- pysat/instruments/rocsat1_ivm.py
- pysat/instruments/template_cdaweb_instrument.py
- pysat/instruments/template_instrument.py
- pysat/instruments/timed_see.py
Trying to make adding new instruments easier.
Added a template for a general instrument, includes code for both xarray and pandas.
Uses pysat functions for list_files.
Added a template for using NASA CDAWeb methods. I expanded the download routine to include support for both sat_id and tag. Previously it only included tag. I updated associated instrument modules using CDAWeb methods.
Updated the supported instruments documentation. Trying a new section just for templates.
There is overlap between the template_instrument and the pre-existing netcdf4_pandas method. There is some distinction, the netcdf4 instrument can actually be used to load files. The template instrument docstrings are a bit more to the point. Perhaps a better basis to start a new instrument. I actually forgot about …
> Added template instruments, related to Issues #94

- pysat/instruments/jro_isr.py
- pysat/instruments/madrigal_pandas.py
Bonus JRO-ISR typo correction.
General madrigal instrument file needs small modification to include list file support. We could require the user to supply an input template string when they instantiate the Instrument object, along with the Madrigal instrument and kindat code.
> General Madrigal Support 

- pysat/instruments/madrigal_pandas.py
Clarified proper use of general Madrigal support in docstrings. Despite my comments in the discussion of this issue, the recent pull (#131) included the underlying functionality.
> Fix for Issue #106

- pysat/instruments/sw_f107.py
Fixed timing bug introduced by reading only the first date/data pair from each line in the 45-day file data blocks.
Reduced duplication by creating a function to read the 45-day file data blocks
Fixed a few obvious PEP8 violations
You can test this code by:
```
import pysat
stime = dt.datetime.today()
sw = pysat.Instrument('sw', 'f107', '45day', update_files=True)
sw.download()
sw.load(date=stime)
print sw.data
```
The date indexes should all be unique and there should be one Ap and F10.7 value for each day.
> Fixed timing bug in 45 day file

- pysat/instruments/pysat_testing.py
This pull requests makes it possible to test the new pysat branch of OCBpy.
- PEP8 changes
- Added OCB tag and sat_id's for the different OCB instruments with appropriate date ranges
- Changed fake file construction to have the same range of dates, but based off of the date provided in test_dates.
> Added OCB testing option

- pysat/instruments/__init__.py
- pysat/instruments/jro_isr.py
- pysat/instruments/nasa_cdaweb_methods.py
- pysat/instruments/omni_hro.py
- pysat/instruments/supermag_magnetometer.py
- pysat/instruments/sw_dst.py
- pysat/tests/test_ftp_instruments.py
- pysat/tests/test_instruments.py
- pysat/tests/test_sw.py
Partial fix for #79.  Replaces `ftplib` with `requests` in cdaweb_methods.download to allow access to cdaweb data via HTTPS.  Allows for future implementation of restful web services with cdaweb server.
> cdaweb access through requests

- .travis.yml
- pysat/tests/test_instruments.py
- pysat/tests/test_utils.py
Fix for #154.
- Updated `.travis.yml` to install latest version of `pyglow` (python 3 compatible). 
- Streamlined `.travis.yml` and removed python version checks since not needed with `pyglow` update.
- Updated `test_instruments.py` to run sgp4 tests in python 3.6.  Should result in an increase in coverage.
When combined with final version of #143, all Travis CI tests should be passing.
> Pyglow install update / Travis streamline

- pysat/instruments/pysat_testadd1.py
- pysat/instruments/pysat_testadd2.py
- pysat/instruments/pysat_testadd3.py
- pysat/instruments/pysat_testadd4.py
- pysat/instruments/pysat_testing.py
- pysat/instruments/pysat_testing2d.py
- pysat/instruments/pysat_testing2d_xarray.py
- pysat/instruments/pysat_testing_xarray.py
- pysat/instruments/pysat_testsmall.py
- pysat/instruments/pysat_testsmall2.py
Closes #86.
Summary of changes
- Updated pysat test instruments filenames to consistently use '%Y-%m-%d' format rather than '/' 
- Added docstring for load routines for all test instruments
- pep8 scrub
> Updates to pysat testing instruments

- pysat/_instrument.py
Uploading for comments.  Addresses #87.
If `pandas.errors.OutOfBoundsDatetime` occurs during file load, does not return data.  Functionally acts as if file is missing (ie, continues with a data gap, but returns a 'Bad datetime for...' rather than a 'No data for...' message to the screen to alert user of a problem.
Ideally, this should scan for the `xarray` equivalent as well.
> Check for bad datetime when loading data

- pysat/_custom.py
- pysat/_instrument.py
Addresses #130.
Starting with xarray 0.11.0, `len` cannot directly be run on a Dataset.  Updates syntax accordingly.
> xarray len deprecation fix

- setup.py
Addresses #187. 
Adds version limits to pandas and xarray for python 2.7. Python 3 and up has no limit largely so Travis CI can keep testing the latest version and update us on when new versions break.
> version limits

- pysat/instruments/sw_f107.py
Changed the way that preliminary F10.7 data files are listed and downloaded
- Changed listing to include only data up to the day before the file was downloaded, since it can't know the future
- Changed the versioning to have two versions for quarterly and yearly, since pysat will ignore earlier versions of files
- Changed date in filename to include the month, since version numbers are not the correct way to count quarters
- Changed the downloads to check for the expected end of the file, since the listing has improved.
> prelim download bugfix

- pysat/instruments/sw_f107.py
LISIRD has updated the web address for F10.7 data.  This addresses the problem found in #211 and #212.
Note that this is a patch.  LISIRD is migrating to using the "Penticton Solar Radio Flux at 10.7cm", which has a higher time resolution.
> update f107 url

- setup.py
An upper limit for `scipy` must be added to maintain testing for python 2.7.   Travis CI will always try to install the latest version unless told otherwise.  The release of scipy 1.3 is not backwards-compatible with python 2.7.  See log of https://travis-ci.org/rstoneback/pysat/jobs/526104564 for example.
While `scipy` is not a pysat requirement, it is a requirement for `xarray`, leading to this problem.
An upper limit for `numpy` has been added as well to prevent this problem from reoccurring when numpy 1.17 is released later this year.
As with #201, upper limits are only imposed on python 2.7 to allow the latest versions to be tested in 3.7.
> Version limits for numpy and scipy

- .travis.yml
Travis CI has updated to using xenial as the default for the 2.7 branch.  This causes apexpy to fail to install (see log in https://travis-ci.org/rstoneback/pysat/jobs/526501730), and tests are not run for pysat.  This is due to 2.7.15 being the default on xenial.
Recommend forcing travis to use 2.7.14 while this is sorted out.
> Travis CI updates - python 2.7.14

- pysat/instruments/timed_saber.py
CDAWeb has updated the directory structure for TIMED/SABER to add new data products.  Rather than add everything now, I'm updating the default dataset so that unit tests can continue uninterrupted.
> bugfix - saber directory

- pysat/instruments/superdarn_grdex.py
Downloads not currently available through DavitPy.  Replacing download routine with a user warning to notify users of this.  Will be fixed when pydarn is released.
> SuperDARN download

- demo/cosmic_and_ivm_demo.py
- docs/conf.py
- pysat/_instrument.py
- pysat/_orbits.py
- pysat/instruments/pysat_sgp4.py
- pysat/instruments/pysat_testing.py
- pysat/instruments/pysat_testing_xarray.py
- pysat/instruments/sw_kp.py
- pysat/tests/test_ftp_instruments.py
- pysat/tests/test_instrument.py
- pysat/tests/test_instruments.py
- pysat/tests/test_meta.py
- pysat/tests/test_orbits.py
- pysat/tests/test_utils.py
- pysat/utils/_core.py
Removed the last of the legacy print statements via 'find all'. Remaining legacy statements all in comments.  Example lines in documentation have been converted to be python 3 compatible. Commented lines have been removed.
> tidy up old print statements

- setup.py
The pandas apocalypse is at hand!
Pandas 0.25 has removed panel.  Adding an upper limit to pandas version to keep the code moving.
> Limit pandas to < 0.25

- CHANGELOG.md
- pysat/instruments/jro_isr.py
- pysat/model_utils.py
- pysat/tests/test_model_utils.py
Description:
Fixes calls to utils routines. Addresses #255 .
Type of change:
Bug fix (non-breaking change which fixes an issue)
How Has This Been Tested?
Try running compare_model_and_inst, collect_inst_model_pairs, or extract_modelled_observations in pysat.model_utils. In the old version these would fail and now they won't.
Download JRO ISR data and apply the pysat.instruments.jro_isr.calc_measurement_loc test when loading the data. The old version would fail and now it won't.
Test Configuration:
OSX Sierra
Checklist:
[x] Make sure you are merging into the develop (not master) branch
[x] My code follows the style guidelines of this project
[x] I have performed a self-review of my own code
[x] I have commented my code, particularly in hard-to-understand areas
[x]  I have made …
> Utils bugfix

- CHANGELOG.md
- pysat/model_utils.py
Fixed bug in compare_model_and_inst that didn't catch certain input errors.
Tested by running a SAMI3 validation with JRO ISR data.
Shorter test below:
```
import xarray as xr
import pysat
da = xr.DataArray(np.random.rand(4, 3),  [('time', pd.date_range('2000-01-01', periods=4)), ('space', ['IA', 'IL', 'IN'])], attrs={'units':'unitless'})
db = xr.DataArray(np.random.rand(4, 3)*np.nan,  [('time', pd.date_range('2000-01-01', periods=4)), ('space', ['IA', 'IL', 'IN'])], attrs={'units':'unitless'})
ds = da.to_dataset(name='model').merge(db.to_dataset(name='inst'))
pysat.model_utils.compare_model_and_inst(ds, inst_name=['inst'], mod_name=['model'])
```
This produces:
```
inst can't calculate stats for 0 finite samples
Out: …
```
> model_utils.py bugfix

- CHANGELOG.md
- pysat/instruments/sw_f107.py
The LASP file format for F10.7 data changed (time format condensed into a single string).  This fixes the way time is cast into a datetime object based on the new file format.  In case people want to access their old files, that option still exists.
Addresses #273 
Test will download data without any errors.
```
import pysat                                                            
f107 = pysat.Instrument('sw', 'f107')                                   
d = pysat.datetime(2009,1,1)                                            
f107.download(d,d)
```
* OS X Sierra
> BUG: LASP file format change

- pysat/_instrument.py
- pysat/tests/test_instrument.py
Addresses # 262
`testInst[:,:]` was broken, so I added label slicing for instruments, which was causing tests to fail.
Modified the instrument test for pandas to slice values instead of index. 
- This change requires a documentation update (possibly)
`pysat/tests/test_instrument.py` passes
* Mac 10.13.6
* miniconda python==3.7.3
> instrument label slicing

- pysat/_files.py
- pysat/tests/test_files.py
Addresses # 268
Refactors empty file filter.
Adds tests to check that file objects and instruments can ignore empty files.
New tests in test_files.py:
- TestInstrumentWithFiles.test_instrument_with_ignore_empty_files
- TestInstrumentWithFiles.test_refresh_on_ignore_empty_files
* MacOS 10.13.6
* Python 3.7.3
* (mini)conda 4.7.11
- [ x] Make sure you are merging into the ``develop`` (not ``master``) branch
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] My changes generate no new warnings
- [ x] I have added tests that …
> Empty file fix

- .travis.yml
- CHANGELOG.md
Back in April, we ran into an issue with installing apexpy on Travis for python 2.7.15.  It is still not known why this was an issue, but it was unique to the automated installation through install requires on the Travis environment.  Issues did not appear on the `apexpy` account for 2.7.15.  This issue was temporarily solved by forcing Travis CI tests to run for python 2.7.14.
This PR manually installs apexpy as part of the Travis CI setup, which circumvents the problem in the testing environment and allows 2.7.15 to be tested.
Tested on Travis CI (change in configuration)
> python 2.7.15 tests in Travis CI

- CHANGELOG.md
- pysat/instruments/methods/sw.py
- pysat/tests/test_sw.py
Fix a bug that presented itself when the list of kp_times was empty (nothing was
downloaded).  Will now return a padded list of NaN.
```
import pysat
standard_inst = pysat.Instrument('sw', 'kp', '')
recent_inst = pysat.Instrument('sw', 'kp', 'recent')
stime = dt.datetime(2014, 2, 19)
etime = dt.datetime(2014, 2, 24)
standard_inst.download(start=stime, stop=etime, freq='M')
recent_inst.download(start=stime, stop=etime)
kp_inst = python.instrument.methods.sw.combine_kp(standard_inst=standard_inst, recent_inst=recent_inst, start=stime, stop=etime)
print(kp_inst)
```
If you take out `freq='M'`, you will get data.  With it in, you should get NaN.
* OS X Sierra
* Python 2.7
> combining kp with no data

- CHANGELOG.md
- pysat/tests/test_utils.py
- pysat/tests/test_utils_coords.py
- pysat/tests/test_utils_time.py
- pysat/utils/__init__.py
- pysat/utils/_core.py
- pysat/utils/coords.py
- pysat/utils/time.py
Back in #272, `season_date_range` was renamed as `create_date_range`.  There should be a deprecation warning for users or packages that use this notation (eg, pysat/pysatMagVect#24).
This pull adds `season_date_range` back to `pysat.utils.time`, which now triggers a deprecation warning and calls the new function.
```
import pysat
start = pysat.datetime(2019,1,1) 
stop = pysat.datetime(2019,1,31) 
pysat.utils.time.create_date_range(start,stop)  
pysat.utils.time.season_date_range(start,stop)   
```
Output should be identical.  Deprecation warning not showing up on my system.  :/
> BUG: add deprecation warning for season_date_range

- CHANGELOG.md
- setup.py
Setup currently overwrites `open` by importing from `codecs`.  Rewriting to keep code more clear.  This was caught in the subpackages.  Updating here for consistency.
Travis CI
- [na] I have made corresponding changes to the documentation
- [na] I have added tests that prove my fix is effective or that my feature works
> STY: do not overwrite open in setup

- CHANGELOG.md
- pysat/instruments/cnofs_ivm.py
Addresses #115.
Currently the C/NOFS IVM cleaning routine only provides data for where the drifts are reliable.  However, it is possible in some cases to have reliable density, composition, and temperature information where the drifts are suspect.  This updates the clean parameters to allow all desired data through while replacing suspect drifts with NaNs.
Instrument quality flags described in https://cdaweb.gsfc.nasa.gov/pub/data/cnofs/cindi/CINDI%20IVM%20Quality%20Flag%20Description.doc (last updated 2018-01-25).
tested ivm.load locally.
> ENH: C/NOFS IVM Cleaning Routine Update

- .travis.yml
- CHANGELOG.md
- pysat/__init__.py
Addresses #295.
Updates the travis implementation of unit tests.  The `pysatData` directory is moved to the /home/travis/build directory, which is both writable and user-independent.  This allows the community to run Travis CI tests on forks of the main branch.  Also cleans up some areas of the travis.yml file.
Pulling from forked pysat to demonstrate.
Tested via Travis CI, since this changes the environment settings there.
- [na] I have added tests that prove my fix is effective or that my feature works
> BUG: Travis update - generalize environment for forks

- CHANGELOG.md
- pysat/instruments/cosmic_gps.py
added S4 scintillation tag and filename handling to the cosmic_gps instrument
Small update to the cosmic_gps instrument to include the tag 'scnlv1' for the 'scnLv1' data from CDAAC.
No existing issue, but the S4 data is an important data product from COSMIC that is not included in the current develop branch.
No new dependencies
- pylint
- Downloaded cosmic data from CDAAC
- ran a seasonal average using the downloaded data
- ran the unit tests successfully (although this instrument is skipped)
OS: CentOS 7 (rhel fedora)
Python 3.7
ran this in a conda environment. Didn't reset any of the files in the ~/.pysat directory so technically not a 100% "clean" pysat install
> S4 scintillation added to cosmic_gps

- CHANGELOG.md
- pysat/instruments/cnofs_ivm.py
- pysat/instruments/demeter_iap.py
- pysat/model_utils.py
Both the DEMETER and CINDI IVM cleaning routines had bugs.
1) C/NOFS IVM:
I tested this by examining the time period used to determine the IVM selection criteria in Burrell, 2012.  The buggy behaviour is shown in the first figure and the fixed behavour is shown in the second
2) DEMETER IAP:
I tested this by running the same selection criteria on the C/NOFS IVM data.  These are labeled as Berthelier et al. Species Threshold in the top figure.
3) model_utils
This has been tested in a year-long model validation run where the bug originally occurred.  You can reproduce it by attempting to load a validation period with a gap in available model files.
* OS X Sierra
* Python 2.7.16
> BUG: IVM clean fix

- CHANGELOG.md
- pysat/_instrument.py
- pysat/model_utils.py
- pysat/ssnl/_core.py
- pysat/ssnl/avg.py
- pysat/ssnl/occur_prob.py
- pysat/ssnl/plot.py
- pysat/tests/test_model_utils.py
- pysat/tests/test_ssnl_ave.py
- pysat/tests/test_ssnl_occur_prob.py
- pysat/tests/test_ssnl_plot.py
- pysat/tests/test_utils.py
- pysat/tests/test_utils_stats.py
- pysat/utils/_core.py
- pysat/utils/coords.py
- pysat/utils/stats.py
- pysat/utils/time.py
Addresses pysat roadmap.  Replaces #308.
- Adds deprecation warnings to `model_utils` and `ssnl`
- Adds tests for deprecation to `model_utls`, `ssnl` and `utils.stats`
- Cleans up some unused variables in tests
- Replaces `xrange` with `range` for python 3.x compatibility (in deprecated function)
- This change adds deprecation warnings
Tested locally via
```
pytest pysat/tests/test_ssnl_ave.py
pytest pysat/tests/test_ssnl_occur_prob.py
pytest pysat/tests/test_ssnl_plot.py
pytest pysat/tests/test_utils.stats.py
```
Python 3.7.3, Mac OS X 10.14.6
> Deprecation warnings

- CHANGELOG.md
- pysat/instruments/cosmic_gps.py
Addresses #312
Fixes a bug where cosmic data downloads crash if a day of data in the requested range is missing.  Also cleans up a few things in the instrument file.
This is outside the Eye of Travis.  Local tests need to be run.
```
import pysat
cosmic = pysat.Instrument('cosmic', 'gps', tag='ionprf')  
start = pysat.datetime(2018, 1, 22)
stop = pysat.datetime(2018, 1, 24)
cosmic.download(start, stop, user=user, password=password)
```
Jan 23 is missing, Jan 22 and 24 exist.  
The code in `develop`  will crash after attempting to download Jan 23.  The list of files obtained by invoking `cosmic.files.files` will not include Jan 22.
The code in this branch should download Jan 22 and Jan 24, and properly update the file list.
**Test …
> BUG: COSMIC downloads

- CHANGELOG.md
- pysat/__init__.py
- pysat/_files.py
- pysat/tests/test_files.py
Addresses 
pysat no longer sets a default directory for data storage.
Travis CI
> ENH: Default pysat directory no longer specified.

- CHANGELOG.md
- pysat/_instrument.py
The downloaded updated files method would incorrectly state it didn't have date inputs when it actually did.
Tested locally downloading ICON IVM files as part of mission processing.
> BUG: Corrected feedback in download_updated_file

- CHANGELOG.md
- pysat/_files.py
The files object is responsible for setting a pysat.Instrument objects date bounds. The code grabbed the first and last file from an unsorted list. I now use the list attached to the Files object.
Travis and local tests.
> BUG: Bad bounds date extraction

- README.md
The Travis badge is still pointing to the old account for the status.
> DOC: typo in badge link

- CHANGELOG.md
- pysat/utils/coords.py
Found a typo in the `utils.coords.scale_units` deprecation warning left over from copy-paste.  Updating to match the current function.
Note that since this function is deprecated and will be removed in python 3.0.0, a twin is not required.
```
import pysat
pysat.utils.coords.scale_units('km', 'm') 
```
Output from develop (wrong): 
```
/Users/jklenzing/anaconda3/bin/ipython:1: DeprecationWarning: utils.computational_form is deprecated, use pysat.ssnl.computational_form instead
```
Output from this branch (correct):
```
/Users/jklenzing/anaconda3/bin/ipython:1: DeprecationWarning: utils.coords.scale_units is deprecated, use pysat.utils.scale_units instead
```
* python 3.7.3
* Mac Os 10.14.6
> BUG: Deprecation Warning in utils.coords.scale_units

- CHANGELOG.md
- pysat/instruments/cnofs_ivm.py
- pysat/instruments/cnofs_plp.py
- pysat/instruments/cnofs_vefi.py
- pysat/instruments/demeter_iap.py
- pysat/instruments/dmsp_ivm.py
- pysat/instruments/icon_euv.py
- pysat/instruments/icon_ivm.py
- pysat/instruments/iss_fpmu.py
- pysat/instruments/jro_isr.py
- pysat/instruments/omni_hro.py
- pysat/instruments/rocsat1_ivm.py
- pysat/instruments/templates/madrigal_pandas.py
- pysat/instruments/templates/template_cdaweb_instrument.py
- pysat/instruments/timed_saber.py
- pysat/instruments/timed_see.py
Followup from #346.  
Replaces `from .methods import ...` with `from pysat.instruments.methods import ...` throughout.
Tested via importing pysat and loading a cdaweb instrument.
* Mac OS 10.14.6
* python 3.7.3
> STY: Robust import from methods

- CHANGELOG.md
- pysat/_files.py
- pysat/tests/test_files.py
Addresses roadmap: migration to `pytest`.
`pytest` does not import tests from classes with an `init` constructor.  This branch rewrites `test_files.py` to avoid these constructors.
Additionally, scrubs `files.py` to be PEP8 compliant, including whitespace, line length, and bare except statements (both should detect `TypeError`).
- Style change (non-breaking change which fixes an issue)
Compared test outputs of both nose and pytest for this file.
```
nosetests -vs pysat/tests/test_files.py
```
yields
```
Ran 67 tests in 17.612s
OK
```
Likewise,
```
pytest -vs pysat/tests/test_files.py
```
yields
```
================================== 67 passed, 227 warnings in 19.57s ===================================
```
All tests are run, all have passed.
* Mac OS X 10.14.6
* …
> TST: pytest compatibility for test_files.py

- CHANGELOG.md
- pysat/instruments/methods/nasa_cdaweb.py
Addresses #348.
`inst.remote_file_list` failed to produce a list of files for some instruments.  This was due to the method it used to choose the expected file preamble.  This has been fixed and cleaned up.
```
import pysat     
ivm = pysat.Instrument('cnofs', 'ivm')
ivm.remote_file_list(year=2009, month=1) 
```
should yield 
```
2009-01-01    cnofs_cindi_ivm_500ms_20090101_v01.cdf
2009-01-02    cnofs_cindi_ivm_500ms_20090102_v01.cdf
2009-01-03    cnofs_cindi_ivm_500ms_20090103_v01.cdf
2009-01-04    cnofs_cindi_ivm_500ms_20090104_v01.cdf
2009-01-05    cnofs_cindi_ivm_500ms_20090105_v01.cdf
2009-01-06    cnofs_cindi_ivm_500ms_20090106_v01.cdf
2009-01-07    cnofs_cindi_ivm_500ms_20090107_v01.cdf
2009-01-08 …
```
> BUG: remote_file_list failures

- CHANGELOG.md
- pysat/instruments/cnofs_ivm.py
The clean routines in the `cnofs_ivm` instrument currently use chained assignment.  This results in multiple `SettingWithCopyWarning` messages while loading data.  This pull rewrites the clean routines to avoid chained assignments by using the `inst.data.loc` command.  This also requires the use of `np.where` to be replaced by boolean indices.
By plotting a sample subset of data (same as in #317), as well as checking the number of cleaned parameters in this range.
```
import matplotlib.pyplot as plt
import pysat
date = pysat.datetime(2009, 4, 10)
def filter_time(inst):
hour = inst.data.index.hour + inst.data.index.minute/60.0
ind = ((hour >= 4) & (hour <= 7.5))
inst.data = inst.data.loc[ind, :]
return
ivm1 = …
```
> BUG: SettingWithCopyWarning in `cnofs_ivm` cleaning routine

- pysat/_constellation.py
- pysat/tests/test_constellation.py
Follow-up to #353 
As part of the removal of seasonal functions in the pysat 3.0.0 roadmap, the functions `add` and `difference` were removed from the `Constellation` class, with the understanding that this functionality would migrate to pysatSeasons.  This PR add deprecation warnings to the 2.2.0 develop branch to warn users of the upcoming shift.
- Deprecation Warning (non-breaking change)
In ipython, try calling these functions to see if a DeprecationWarning is raised.
Also, `pytest -vs pysat/tests/test_constellation.py`
> ROADMAP: Add deprecation warnings for constellation analysis operations

- setup.py
Addresses ROADMAP
Removes upper limit for pandas.  Travis CI now testing with pandas 1.0.0.  :)
The upper limit was in place due to the `Panel` deprecation, which has been dealt with in this branch.
Since support for python 2.7 is dropped in this version, cleaned up the setup file as well.
Note: Some uncovered areas such as the cosmic instruments may still require local testing.
- requirements change (non-breaking change which adds functionality)
tested via Travis CI
* Version number
> ROADMAP: Remove upper limits on pandas for pysat 3.0.0

- .travis.yml
- CHANGELOG.md
- pysat/_custom.py
- pysat/tests/test_custom.py
Addresses #361.  Pysat 2.2.0 partner to #378.
- Adds a deprecation warning to `custom.add`.
- Adds temporary caps to travis.yml to play better with pandas and xarray for pysat 2.x.
- Deprecation Warning
Travis CI
> ROADMAP: Deprecate custom.add

- CHANGELOG.md
- pysat/instruments/methods/madrigal.py
Updated Madrigal downloads to use madrigalWeb subroutines instead of calling the python module externally.
Addresses the issue where certain set ups have trouble finding the command-line interface provided by the `madrigalWeb` module.
- This is a maintenance issue that refactors the way we interact with `madrigalWeb`.
Tested by downloading a year of JRO ISR drift data.
* Operating system: OS X Sierra
* Version number Python 2.7 and 3.7
> MAINT: updated madrigal downloads

- .travis.yml
- CHANGELOG.md
- pysat/instruments/cosmic_gps.py
Fixes non-unique data and file times in COSMIC
Addresses # 363, 364
There can be multiple profiles or files for a given time. The cosmic_gps code was 
updated to provide unique times.
Added unique time checks within the code itself to self-monitor for issues. Tested
on multiple days and file types, locally.
* macOS 10.15.3
> Cosmic time bug

- pysat/utils/time.py
season_date_range accepts a freq keyword but it is not passed along to the underlying method so it doesn't work as expected.
Direct execution of method.
> BUG: freq keyword not passed through in season_date_range

- .travis.yml
- CHANGELOG.md
- pysat/_instrument.py
- pysat/instruments/cosmic_gps.py
- pysat/instruments/pysat_testing.py
- pysat/tests/test_instrument.py
Resolves # 292
pysat passes non-pysat keywords provided at instantiation to the underlying load routine for a particular data set. If a user mis-typed a pysat keyword it would get lost without user notice. Now, if a non-pysat keyword is provided and if that keyword is not supported by the underlying load routine an error is raised. By supported that means in the method signature.
The altitude_bin keyword was not properly supported by the cosmic_gps routine. Fixed. …
> ENH: Keyword Check at Instantiation

- docs/supported_instruments.rst
DE2 Instruments weren't showing up in the documentation. Found a spacing issue that is updated here.
ReadTheDocs running now
> DOC/BUG: DE2 Documentation

- CHANGELOG.md
- pysat/instruments/jro_isr.py
- pysat/utils/coords.py
xarry assign no longer allows inplace, use keyword arguement assignemnt instead.  Also fixed try/except loop that caught everything.
```
import pysat
jro = pysat.Instrument('jro', 'isr', 'drifts')
jro.custom.add(pysat.instruments.jro_isr.calc_measurement_loc, 'modify')
jro.load(yr=2014, doy=20)
print([kk for kk in jro.data.data_vars.keys()])
```
With success this yields: `['year', 'month', 'day', 'hour', 'min', 'sec', 'recno', 'kindat', 'kinst', 'ut1_unix', 'ut2_unix', 'range', 'gdlatr', 'gdlonr', 'spcst', 'pl', 'cbadn', 'inttms', 'azdir7', 'eldir7', 'azdir8', 'eldir8', 'jro14', 'jro15', 'jro16', 'nwlos', 'vipn2', 'dvipn2', 'vipe1', 'dvipe1', 'vi72', 'dvi72', 'vi82', 'dvi82', 'paiwl', …
> BUG: assign no longer allows inplace

- pysat/_instrument.py
- pysat/_meta.py
- pysat/tests/test_instrument.py
- pysat/tests/test_meta.py
- pysat/tests/test_utils.py
Develop version of #377 
* Removed `__setattr__` and `__getattr__`, which implicitly moved  Instrument attributes onto attached Meta object.
* Added `__setattr__` method to Meta. 
- New Feature 
checks that Meta.mutable flag prevents new attributes from being added
checks that meta's `@properties` will work regardless of `mutable` flag
Checks that instrument attributes are not overridden on load
removed tests checking implicit move of attributes from `inst.<attr>` to `inst.meta.<attr>`
tests that instrument's meta is made immutable upon load.
overrides the default behavior by setting inst.meta.mutable=True. Removed part of this test related to implicit transfer of `inst.<attr>` to `inst.meta.<attr>`
> ENH: preserving metadata attributes upon load and adding mutable flag

- CHANGELOG.md
- pysat/_instrument.py
- pysat/_meta.py
- pysat/tests/test_instrument.py
- pysat/tests/test_meta.py
- pysat/tests/test_utils.py
Addressing # 374
* Removed `__setattr__` and `__getattr__`, which implicitly moved  Instrument attributes onto attached Meta object.
* Added `__setattr__` method to Meta. 
- New Feature 
checks that Meta.mutable flag prevents new attributes from being added
checks that meta's `@properties` will work regardless of `mutable` flag
Checks that instrument attributes are not overridden on load
removed tests checking implicit move of attributes from `inst.<attr>` to `inst.meta.<attr>`
tests that instrument's meta is made immutable upon load.
overrides the default behavior by setting inst.meta.mutable=True. Removed part of this test related to implicit transfer of `inst.<attr>` to `inst.meta.<attr>`
> removing Instrument to Meta attribute assignment

- .travis.yml
- CHANGELOG.md
- pysat/__init__.py
- pysat/_instrument.py
Updates to the netcdf4 export function. Improves compatibility with later netCDF4 libraries and provides warnings for unsafe casting of Fill Values in netcdf4 export.
Addresses
NetCDF export fails with current versions of the netCDF4 library with an HDF error. This is because of a conflict between h5py and the hdf libraries from the netCDF4 package. This is resolved by importing netCDF4 in  __init__.py so that the netCDF4 hdf libraries are loaded first.
Currently, the netcdf4 export function casts fillvalues to match the value of the column, but this casting may be unsafe. The most common example is if a nan is being casted to an integer it will become a zero. If zero is a valid value for the column, this will result in the masking of valid data in the exported netCDF file. Added a …
> Netcdf4 export

- pysat/instruments/de2_nacs.py
- pysat/instruments/de2_wats.py
Copy and paste failure from initial PR.  de2_nacs and de2_wats mistakenly given `idm` as name.
NOTE: no updates to changelog since the 2.2.0 changes are not released.
Found while writing new unit tests in #391.
> BUG: DE2 names for wats and nacs - pysat 3.0.0 edition

- .travis.yml
New versions of `pyparsing`, `kiwisolver`, and `beautifulsoup4` have been released which do not support tests on python 2.7.  Limiting these in the travis setup and clarifying the block of pip installs that should not go into the develop-3 version.
Discovered in #405, but opening a separate pull to aid in tracking changes.
- Bug fix -- Testing environment (non-breaking change which fixes an issue)
On Travis CI.
> TST: limits on travis for python 2.7 tests

- CHANGELOG.md
- pysat/instruments/pysat_testing.py
- pysat/instruments/pysat_testing2d.py
- pysat/instruments/pysat_testing2d_xarray.py
- pysat/instruments/pysat_testing_xarray.py
Closes #410.
- Adds a constant altitude of 400 km to the test instruments.
- Updates `pysat_testing2d_xarray` to use `altitude_profile' and 'altitude_profile2' for the profile data.
Required for pysat/pysatModels#34.
via pytest.
Also by 
```
import pysat
test = pysat.Instrument('pysat', 'testing')
test.load(date=pysat.datetime(2009, 1, 1))
print(test)
```
which should result in 'altitude' appearing in the list of variables.  I did this for each of the four satellite objects without error.
* Mac OS X 10.15.4
* python 3.7.3
> ENH: Adds 'altitude' to test instruments

- CHANGELOG.md
- pysat/tests/test_ssnl_ave.py
With numpy 1.18, `linspace` no longer accepts a float value for the number of steps, but requires an integer.  This currently only affects some tests in `test_ssnl_ave`, which are fixed here.  This does not affect pysat 3.0, as these routines have been removed.  This is addressed in pysat/pysatSeasons#17.
via unit tests, since these are what are broken.
> BUG: numpy 1.18 compatibility

- CHANGELOG.md
- pysat/_instrument.py
In the name of reducing the impending madness whilst reading the logs, this PR changes the trigger conditions in the develop-3 branch.  This will ultimately be removed upon release, but other codes in the pysat ecosystem rely on this branch for testing.  
The DeprecationWarning is currently triggered upon every instrument instantiation, which has resulted in "some" additional warnings in the test logs.  This PR moves it so that it is only thrown if an instrument violates the strict_flag conditions. 
Tested locally by comparing warnings on test_instrument.py.  Reduced warnings from 346 to 4.
> WRN: Adjust strict_time_flag DeprecationWarning trigger

- CHANGELOG.md
- pysat/_files.py
- pysat/instruments/cosmic_gps.py
- pysat/tests/test_instrument.py
Addresses #417 
With pandas 2.0 (probably released next year), the default dtype for pandas.Series(None) will shift from 'float64' to 'object'.  Getting ahead of the code to make sure nothing breaks.
This pull specifies a dtype in the four instances we invoke an empty series.  Three of these are associated with file lists, so object is chosen as the default.  The fourth is part of a unit test that expects a number, so this is tagged as float64 (it breaks if this is specified as an object).
- Non-breaking change to maintain code
Tested via pytest.
> MAINT: specify dtype in pds.Series(None)

- CHANGELOG.md
- pysat/instruments/sw_f107.py
Addresses # 398
import pysat
f107 = pysat.Instrument('sw', 'f107', tag='prelim', update_files=True)
import datetime
stime = datetime.datetime(2016, 6, 11, 0, 0)
etime = datetime.datetime(2016, 6, 17, 0, 0)
f107.download(stime, etime)
f107.load(date=stime)
works on my local machine. 
macOS 10.15.3
> F107 date parsing issue

- pysat/instruments/pysat_testmodel.py
Coordinate name 'longitude' misspelled for two of the data values.
```
import pysat
model = pysat.Instrument(inst_module=pysat.instruments.pysat_testmodel)
model.load(yr=2009, doy=1)
mdat='slt'
dims = [kk for kk in model.data.data_vars[mdat].dims]
print(dims)
```
In new version, you get: `['time', 'longitude']`.  In the old version you get `['time', 'longtiude']`
* Version number 3.7
> BUG: coordinate name

- CHANGELOG.md
- pysat/instruments/sw_kp.py
Addresses #417. Follow on to #419.
Found one more use of an empty pds.Series in the code that I missed in the last pull. This use works for either 'float64' or 'object'.  Since numbers ultimately go in, using 'float64'. 
Also found multiple uses of `pds.Series()` in the demo codes as well.  Tested those using both options, no breaking changes in code.  Since these are not run in the unit tests, leaving them alone for now.
- Maintenance fix (non-breaking change for continuity in future versions of pandas)
via pytest locally and on Travis.
> MAINT: empty pds.Series in sw_kp

- pysat/instruments/pysat_testmodel.py
Coordinate name 'longitude' misspelled for two of the data values.
```
import pysat
model = pysat.Instrument(inst_module=pysat.instruments.pysat_testmodel)
model.load(yr=2009, doy=1)
mdat='slt'
dims = [kk for kk in model.data.data_vars[mdat].dims]
print(dims)
```
In new version, you get: `['time', 'longitude']`.  In the old version you get `['time', 'longtiude']`
* Version number 3.7
> BUG: testmodel coordinate name

- CHANGELOG.md
- pysat/_instrument.py
- pysat/tests/test_instrument.py
When using `print(inst)` on a pysat instument with orbital information, the printout always responds with 'Orbit properties not set', regardless of instrument settings.  This fixes that so the expected behaviour is maintained.
This also expands the unit tests for the repr functions to check that the appropriate output is generated for each path through the function.
```
import pysat
info = {'index': 'mlt', 'kind': 'local time', period=97}
testInst = pysat.Instrument('pysat', 'testing', orbit_info=info)
testInst.load(2009, 1)
testInst.orbits.next()
print(testInst)
```
In the fix, orbtial info is displayed under 'Orbit Settings'.  In the old version, 'Orbit properties not set' is displayed incorrectly.
* Mac OS X …
> BUG/TST: Fixed display of orbital info in print(inst) / expand unit testing

- .travis.yml
Fixes the bug when using conda to install coveralls in Travis CI.  See #429 for more more details.
In currently open PRs, no coveralls reports are listed under the checks.  If this works, coveralls should report below.
> BUG: use coveralls from pip in Travis CI -- pysat 2.2.0 edition

- .travis.yml
The last 30 or so builds of pysat have dropped coveralls reports.  This occurs around the point we switched to using conda.  Conda is installing older (pre-2.0) versions of coveralls, which crash on some of the Travis environments.  This installs coveralls from pip rather than conda to get a working version.
See recent builds here:
https://coveralls.io/github/pysat/pysat
If coveralls reports under the checks, it's working.
> BUG/TST: Fix for coveralls and conda

- CHANGELOG.md
- pysat/__init__.py
- pysat/instruments/__init__.py
- pysat/instruments/methods/__init__.py
Addresses #150 
- Removes the wildcard imports from the various `__init__` files. 
- Specifies absolute paths for imports
- Removes convenience methods from datetime and pandas now that pysatCDF is compliant
- Style changes
Tested that instruments load properly in ipython.  Travis CI tests.
> STY: Remove relative imports, wildcard imports, and convenience methods

- CHANGELOG.md
- docs/tutorial.rst
- pysat/_custom.py
- pysat/tests/test_custom.py
- pysat/tests/test_orbits.py
Improved the custom function input by:
- improving inline comments,
- adding and fixing style of docstrings,
- changing `attach` input to use keyword arguments for function inputs,
- changed the default `kind` to "modify", since that is the most frequently used option,
- changed "add" data saving to take the dict key "name" before the dict key "data" metadata,
- added an input check for the position specifier that defaults to placing
placing the function at the end if appropriate input isn't provided,
- changed style of a ValueError statement construction to conform with
pysat norms,
- streamlined existing `test_custom.py` unit tests,
- added unit test to cover new logging output, and
- updated documentation to reflect new behaviour.
Addresses #428 
Please delete options that are not …
> STY: custom input improvement

- CHANGELOG.md
- pysat/instruments/__init__.py
- pysat/instruments/pysat_testing2d.py
- pysat/instruments/pysat_testing2d_xarray.py
- pysat/instruments/pysat_testmodel.py
Including the test instruments in the main package to help streamline testing for non-pysat packages (ocbpy, etc) that include pysat as part of their unit tests.
Minor updates to structure now that test instruments are checked for tags and sat_ids.
via travis ci
> ENH: include test instruments in main package

- CHANGELOG.md
- pysat/instruments/methods/nasa_cdaweb.py
- pysat/instruments/omni_hro.py
- pysat/tests/test_methods_cdaweb.py
Addresses #426.
Summary
- Uses `remote_file_list` to see if files exist before requesting a download for non-`multi_file_day` instruments for cdaweb
- If a connection error is still generated, append the error message to suggest trying a smaller date range
- Included standard `remote_file_list` method for omni data
NOTE: This code can be further simplified, but this requires a breaking change for keywords in `remote_file_list`.  This will be addressed in the pysat 3.0.0 version, and appropriate DeprecationWarnings have been added here.
Ran the tests outlined in #426 in ipython.
* Mac OS X 10.15
* python 3.7.3
> BUG: Improved CDAWeb downloads

- CHANGELOG.md
- pysat/_instrument.py
- pysat/instruments/methods/nasa_cdaweb.py
- pysat/instruments/omni_hro.py
- pysat/tests/instrument_test_class.py
- pysat/tests/test_methods_cdaweb.py
Addresses #436.
- Improves consistency of remote_file_list syntax.  Method now accepts `start` and `stop` as keywords.
- Includes bugfix from pysat 2.2.0 branch (#434).
- Add unit tests for error checks in cdaweb methods
- inlcudes recent updates from pysat 2.2 to the changelog
Via procedure outlined in #426.
> ENH/BUG: Updates to NASA CDAWeb methods -- pysat 3.0.0

- CHANGELOG.md
- pysat/_meta.py
NOTE: I don't have write permissions to pysat so I'm simply creating a merge request on the netcdf4-export3 branch. The intention was to fix the level1b issue so I built this fix on top of that branch.
These fixes in _meta.py will handle unconverted byte strings (e.g. b"example") from bytes to UTF-8 standard strings for python 3. The fix will also convert completely empty metadata to an empty string in the case that processing meta data causes the process to fail.
Necessary for run of cosmic-2 and full_ivm python 3 branches.
- Test A
Produce a fraction of a level2 cosmic-2 file. Using the command line command from cosmic-2 (as if using the project's master branch on …
> Handle the byte strings and empty strings from instrument meta data properly.

- CHANGELOG.md
- pysat/_files.py
- pysat/instruments/cosmic_gps.py
- pysat/tests/test_files.py
Addresses #337.
`parse_delimited_files` currently assumes all variables must be integers.  Some instruments may use strings.  This improves compatibility with other instrument types to maintain variable type in the routine if integer conversion can't be done.  Adds a `version` variable as a string to the unit tests.
Also changes how this is implemented in the cosmic files.  The existing `shift_uts` variable adds fractional seconds to the time stamp of the file for sorting purposes.  Removed the treatment of GNSS ID as seconds since this is not needed for filenames and is the source of the bug in the issue.
Note that this does not fix potential non-unique timestamps within the data.  A FIXME comment has been added to upgrade to xarray down the line.
Updates for style and PEP8 in …
> BUG: recognize string variables in parse_delimited_files

- CHANGELOG.md
- pysat/_instrument.py
- pysat/_meta.py
- pysat/tests/test_meta.py
Addresses issue where exported netCDF files contain unnecessary metadata. Due to the nature of the pandas, if a metadata parameter is added, it will be added to all variables. This may not always be the desired behavior. If no value is assigned to the parameter, it will be assigned nan. Thus, we can remove these parameters by not exporting metadata parameters with a value of nan. If a parameter does need to be exported with a value of nan, the name of the parameter must be added to the export_nan list that is now a part of the meta object.
Please delete options …
> NetCDF Export NaN metadata

- pysat/_instrument.py
Alternate method for getitem_xarray.  This should be more compatible and allow either 'time' or 'Epoch' to be used as the key index.  Should be more backwards-compatible for when these are ported to pysat 2.2.
Note this is several commits behind #441.  This allows the test instruments to be maintained for 2.2, though we may want to upgrade in 3.0.
> ENH: allow time or Epoch in getitem_xarray

- CHANGELOG.md
- pysat/_files.py
- pysat/instruments/methods/testing.py
- pysat/instruments/pysat_testing.py
- pysat/instruments/pysat_testing2d.py
- pysat/instruments/pysat_testing2d_xarray.py
- pysat/instruments/pysat_testing_xarray.py
- pysat/instruments/pysat_testmodel.py
- pysat/tests/test_instrument.py
Supports unit tests for several uncovered functions in `pysat._instrument`.  All tests use the testing instruments to simulate the usage of `remote_file_list` and `remote_file_range`
- Adds a `remote_file_list` function to the testing instruments to simulate a slightly longer list of files on the remote server
- Cleans up a few style issues
NOTE: the original intent of this pull was to cover `download_updated_files`.  However, the function can be run but not tested, as the only output will go to the log, and scanning the log for this specific test is not viable.  Pushing off those changes to keep this branch from getting stale.
- New unit tests (non-breaking change which adds functionality)
via pytets
* Mac OS X 10.15.4
* python 3.7.3
> TST: Unit tests for `remote_file_list` and `remote_date_range`

- CHANGELOG.md
- pysat/tests/test_utils_coords.py
- pysat/utils/coords.py
Addresses #167 (partial)
Several functions in coords will be removed in pysat 3.0.0.  These functions will move to pysatMadrigal.  This pull adds deprecation warnings and tests for them.
- geodetic_to_geocentric
- geodetic_to_geocentric_horizontal
- spherical_to_cartesian
- global_to_local_cartesian
- local_horizontal_to_global_geo
- ROADMAP changes
locally via pytest
> DEP: Add deprecation warnings for functions in coords

- CHANGELOG.md
- pysat/instruments/cnofs_ivm.py
- pysat/instruments/cnofs_plp.py
- pysat/instruments/cnofs_vefi.py
- pysat/instruments/de2_lang.py
- pysat/instruments/de2_nacs.py
- pysat/instruments/de2_rpa.py
- pysat/instruments/de2_wats.py
- pysat/instruments/iss_fpmu.py
- pysat/instruments/methods/general.py
- pysat/instruments/methods/nasa_cdaweb.py
- pysat/instruments/omni_hro.py
- pysat/instruments/rocsat1_ivm.py
- pysat/instruments/timed_saber.py
- pysat/instruments/timed_see.py
- pysat/tests/test_methods_cdaweb.py
As part of the pysat 3.0.0 overhaul, the `list_files` routine from `instruments.methods.nasa_cdaweb` has been moved to `instruments.methods.general`.  While this change should not affect standard users, in theory it could affect users with custom instruments.  This will be frequently called, so I'm not sure we want it to be thrown every time.  Thoughts?
EDIT: After discussion, moving the method `'list_files` to general now, but leaving a method with the same name in the cdaweb methods to throw a DeprecationWarning and then call the new method.  This allows for a smoother transition, while only using a DeprecationWarning when needed.  Updating current instruments to use the new method, except for ICON instruments, which will be handled in #457.
- New warning
```
try: …
```
> DEP: Add DeprecationWarning for nasa_cdaweb.list_files 

- CHANGELOG.md
- pysat/_instrument.py
- pysat/instruments/icon_euv.py
- pysat/instruments/icon_fuv.py
- pysat/instruments/icon_ivm.py
- pysat/instruments/icon_mighti.py
- pysat/instruments/pysat_testing.py
Opening a new pull for this discussion.  This should push it closer to @rstoneback's syntax, but assuming that the default is to remove the file names.
Tested locally by loading each instrument.  Example:
```
sat_ids = {'': ['vector_wind_green', 'vector_wind_red'], 
'a': ['los_wind_green', 'los_wind_red', 'temperature'], 
'b': ['los_wind_green', 'los_wind_red', 'temperature']}  
for sat_id in sat_ids.keys(): 
for tag in sat_ids[sat_id]: 
inst = pysat.Instrument('icon', 'mighti', sat_id=sat_id, tag=tag, keep_original_names=True) 
inst.load(2020, 2) 
print(inst) 
for sat_id in sat_ids.keys(): 
for tag in sat_ids[sat_id]: 
inst = pysat.Instrument('icon', 'mighti', sat_id=sat_id, tag=tag) 
inst.load(2020, 2) 
print(inst) 
```
The first …
> STY: streamline keep_original_names in icon instruments

- pysat/_instrument.py
- pysat/instruments/__init__.py
- pysat/instruments/icon_euv.py
- pysat/instruments/icon_fuv.py
- pysat/instruments/icon_ivm.py
- pysat/instruments/icon_mighti.py
- pysat/instruments/methods/general.py
- pysat/instruments/pysat_testing2d_xarray.py
- pysat/tests/test_methods_general.py
- pysat/utils/_core.py
The clean routines for the icon instruments need to be updated.  Comparing with cnofs_ivm, we need to look at inst.clean_level rather than declaring a separate kwarg.  Since default was `None`, the clean routines were skipped.
NOTE: these will not run if the keep_original_names flag is set, as they are based on the trimmed names.  This needs to be fixed.
Other NOTE: working in the 3.0 branch as I can run these tests locally and they take half the time.
Simple local test:
```
import pysat
ivm = pysat.Instrument('icon', 'ivm', sat_id='a')
ivm.load(2020, 1)
idx, = np.where(ivm['RPA_Flag'] == 2)
len(idx) == sum(np.isnan(ivm['Ion_Velocity_X'][idx]))
```
If the clean routines are being run, then Ion_Velocity_X should be NaN wherever the RPA_Flag is 2.  For this date, this …
> BUG: clean not run in icon -- 3.0 version

- CHANGELOG.md
- pysat/_instrument.py
- pysat/tests/test_instrument.py
Addresses #91 
Includes a .rename variable method attached to the Instrument object. Renames variables for both data and metadata, keeping both objects in sync. Includes support for changing the name of variables in higher-order datasets forced into pandas. Examples are included in the docstring.
This feature could be sneakily snaked into v2.2 to support changing ICON variables to something easier to work with.
- Developed new tests included in test_instrument
- Ran pytests locally
> ENH: Method for renaming variables

- pysat/_constellation.py
- pysat/_custom.py
- pysat/_meta.py
- pysat/instruments/dmsp_ivm.py
- pysat/instruments/jro_isr.py
- pysat/instruments/methods/madrigal.py
- pysat/instruments/methods/nasa_cdaweb.py
- pysat/instruments/supermag_magnetometer.py
- pysat/model_utils.py
- pysat/ssnl/_core.py
- pysat/ssnl/avg.py
- pysat/ssnl/occur_prob.py
- pysat/ssnl/plot.py
- pysat/tests/test_methods_cdaweb.py
- pysat/utils/coords.py
- pysat/utils/stats.py
- pysat/utils/time.py
- Adds deprecation info to docstrings according to numpydoc
- minor formatting issues.
- Fixes a test that required pytest
make html
> DOC/TST: deprecation in docstring, format stuff, test compliance

- CHANGELOG.md
- pysat/instruments/rocsat1_ivm.py
ROCSAT data has disappeared from the server.  Flipping the test flag and adding a user warning for now until the data reappears somewhere.
NOTE: this really should probably use the logger, but none of the other instruments do.  If we change over all instruments (here and elsewhere), this would require the corresponding unit test (`test_download_warning`) to use `caplog` instead of `with warnings.catch_warnings`
via pytest
> BUG: Rocsat tests

- CHANGELOG.md
- pysat/tests/test_sw.py
pandas 1.1.0 has been incorporated into the unit tests, and some updates to how indices are called are required.  
pandas no longer allows the call of `kp_inst['Kp'][kp_inst['Kp']]`.  This is only incorporated in the unit tests as part of several assert statements.  These have been updated.
tested via pytest.  `develop-3` passes locally with pandas 1.0.5, but not 1.1.0.  The changes in this branch pass in both versions.
> BUG: pandas 1.1.0 compatibility

- CHANGELOG.md
- pysat/_files.py
- pysat/instruments/cosmic_gps.py
- pysat/instruments/methods/icon.py
- pysat/instruments/methods/nasa_cdaweb.py
- pysat/tests/test_files.py
- pysat/utils/__init__.py
- pysat/utils/files.py
- setup.cfg
Addresses #336 
- Moves the methods from `pysat._files` to `pysat.utils.files`.  Includes deprecation warnings for the old methods, which point to the new methods.
- Includes a flake8 sweep of `_files.py` and `test_files.py`, as well as the removal of those exceptions.
via pytest
> ENH: move file methods to utils.files

- CHANGELOG.md
- pysat/instruments/methods/demeter.py
- pysat/instruments/methods/general.py
- pysat/instruments/methods/icon.py
- pysat/instruments/methods/nasa_cdaweb.py
- pysat/instruments/methods/sw.py
- pysat/instruments/methods/testing.py
- pysat/instruments/templates/netcdf_pandas.py
- pysat/instruments/templates/template_cdaweb_instrument.py
- pysat/instruments/templates/template_instrument.py
- Applies new docstring style to methods and templates.
- Declares integer in for input in `convert_timestamp_to_datetime` to supress futurewarnings in python 3.8 (~10,700 warning messages :scream: )
This is the last PR needed before instruments can be migrated out.
via pytest, as well as make html
> DOC/STY: Update instrument methods and templates based on 2.2 release

- CHANGELOG.md
- pysat/instruments/methods/general.py
The general method for listing_files, `pysat.instruments.methods.general` does not correctly support the advertised two_digit_year_break keyword.
Tested in practice using TEC Instrument
> BUG: GNSS Integration

- pysat/instruments/methods/testing.py
- pysat/instruments/pysat_testing.py
- pysat/tests/instrument_test_class.py
- pysat/tests/test_files.py
- Adjusts the local test instruments to engage all options in `instrument_test_class`
- Removes default package in `instrument_test_class`
- Adds a deprecation warning test for `search_local_system_formatted_filename`, which was deprecated in #505 
After the removal of the instruments in #515, some covered areas (instruments without download support, non strict_time data) have become uncovered.  These are still engaged by the downstream packages, but troubleshooting becomes difficult in changes in pysat manifest downstream and are not tested here.
Also, when working with downstream packages, the test class should error if a package is not supplied.  Otherwise, tests are run on the main pysat instruments and a false positive will be seen downstream.  Better to have an error right away to …
> TST: updates to tests in core code after instrument migration

- .zenodo.json
Partially Addresses #495 
* Update Carey's Zenodo entry with an ORCID identifier.
* Remove an extra `}` that was causing JSON validation to fail. 
I checked that the JSON file is valid JSON: 
```
% git log -1 --pretty=oneline
6a03a40c5aa4dde9b7ed0177b51609543dcde519 (HEAD -> zenodo-carey, origin/zenodo-carey) style(zenodo): Remove extra bracket
% git diff
% json_pp -V 
4.04
% json_pp < .zenodo.json > /dev/null && echo OK || echo FAIL 
OK
% 
```
* Operating system: Fedora 32
* Version number: pysat 3.0.0, json_pp 4.04
> Update Carey's Zenodo entry and style

- CHANGELOG.md
- pysat/_custom.py
- pysat/_files.py
- pysat/_instrument.py
- pysat/instruments/methods/general.py
- pysat/tests/test_custom.py
- pysat/tests/test_files.py
- pysat/tests/test_instrument.py
Currently, when you have a gap in monthly files the file routine assumes that the last monthly file between two dates lasts for the entire period of time.  The changes introduced here fix that problem.
Partially addresses #58 
Created this branch off of PR #523, so that needs to be merged first.
My 1 min omni hro data has some gaps in it.  Go check yours out and if it doesn't have a gap, move one file away temporarily to create one.
```
import pysat
out = pysat.instruments.methods.general.list_files('1min', '', '{:s}/omni/hro/1min/'.format(pysat.data_dir), supported_tags = {'': {'1min': 'omni_hro_1min_{year:4d}{month:02d}{day:02d}_v01.cdf'}}, fake_daily_files_from_monthly=True)
print(out)
``` …
> BUG: Monthly file padding fix

- pysat/__init__.py
- pysat/_instrument.py
- pysat/tests/instrument_test_class.py
- pysat/tests/test_registry.py
- pysat/utils/registry.py
Addresses #516 and more
Updates the register package.
- Changed format of .pysat/user_modules.txt to store packages by platform and name
- Changed format of pysat.user_modules to be a dict of dicts keyed by platform and name
- Restricted `pysat_*` instruments to those internal to pysat.instruments
- Changed use of registry so that only requested module needs to be imported
- Added support to add multiple packages at once using strings
- Added support to register an entire instrument package like `pysat.instruments` or `pysatModels.models`
- Added support to remove all instrument modules from registry by platform name along
- Added support to remove multiple packages by string platform and name
- Modified method calls and docstrings
- Raises error if a module is removed but not registered …
> Registry update

- CHANGELOG.md
- docs/api.rst
- pysat/_constellation.py
- pysat/_custom.py
- pysat/_files.py
- pysat/_instrument.py
- pysat/_meta.py
- pysat/utils/_core.py
- pysat/utils/coords.py
- pysat/utils/registry.py
- pysat/utils/time.py
Addresses #486, #528 (partial)
- Finishes the docstring scrub for improved formatting (#486)
- Adds new methods under `utils` to the api documentation (#528)
```make html``` followed by visual inspection of the api document in a web browser
> DOC: update docstrings for 3.0, add new methods to registry

- CHANGELOG.md
- pysat/_instrument.py
- pysat/_meta.py
- pysat/utils/_core.py
This PR reduces the number of warnings raised from 1808 to 1749 and Addresses #546 
Please pay special attention to the changes in the documentation (files, inline comments, and docstrings) to ensure they are clear and make sense.
Formerly, this raised a pandas Warning, and now it won't
```
import pysat
inst = pysat.Instrument("pysat", "testing", clean_level="clean")
inst['new_data'] = inst['mlt']
inst['hi'] = inst['mlt']
inst.meta['hi'] = inst.meta['new_data']
```
Also, running the unit tests will show the reduction in Warnings.
* Operating system: OSX Mojave
* Any details about …
> Address Warnings from use of dependent packages

- CHANGELOG.md
- pysat/tests/instrument_test_class.py
The inspection from `assert` statements are not always informative.  This has proved problematic when trying to figure out what's going on (see, for example, Issue #550).
- Ran unit tests locally
- Registration of instrument module with old attribute (sat_id) on current pysat branch.  Previously, this would fail thusly:
```
65         # Check for presence of basic instrument module attributes
66         for mattr in self.module_attrs:
---> 67             assert hasattr(module, mattr)
68             if mattr in self.attr_types.keys():
69                 assert isinstance(getattr(module, mattr),
AssertionError: 
```
Now, there will be a message that tells you `inst_ids` is missing. …
> Clearer error messages

- pysat/__init__.py
- pysat/_custom.py
- pysat/_instrument.py
- pysat/_meta.py
- pysat/_orbits.py
- pysat/instruments/templates/template_instrument.py
- pysat/tests/test_files.py
- pysat/tests/test_utils.py
Addresses #564
- Removes python 2.7 syntax (__future__ )
- Removes nickname for `importlib.reload` (left over from 2.7 compatibility days)
- Consistency in import order
Tested via pytest of the changed files locally.
> STY: python 2.7 cleanup

- CHANGELOG.md
- docs/tutorial_basics.rst
- pysat/_files.py
- pysat/_instrument.py
- pysat/instruments/methods/general.py
- pysat/instruments/pysat_testing.py
- pysat/instruments/pysat_testing2d.py
- pysat/instruments/pysat_testing2d_xarray.py
- pysat/instruments/pysat_testing_xarray.py
- pysat/instruments/pysat_testmodel.py
- pysat/instruments/templates/template_instrument.py
- pysat/utils/files.py
Currently, the Instrument input `*args` is not used and `**kwargs` can only be used to supply optional kwargs for the load routine.  This PR removes unused input arguments and allows optional kwargs to specify information for any of the standard Instrument methods.
Addresses #531 
- Bug fix and Breaking Change that fixes an issue
Tested with https://github.com/pysat/pysatMadrigal/pull/20 and local unit tests.
> Improve Instrument input

- CHANGELOG.md
- pysat/instruments/dmsp_ivm.py
- pysat/instruments/methods/madrigal.py
Addresses #567
Madrigal metadata about an experiment gets loaded as a combined data type, like  dtype=('Notes', 'S80'), which netCDF4 doesn't appreciate. Updated the code to simplify compound data types into a string only. 
I followed the directions in #567 and was able to produce a file.
> BUG: Format Madrigal Metadata

- CHANGELOG.md
- docs/installation.rst
Addresses #592 
Updates documentation to include numpy version restriction. There is a version restriction on numpy with setup.py, however, numpy must be installed before setup.py can be run.
- Bug fix in Documentation (non-breaking change which fixes an issue)
- Ran a new installation on my local system using a fresh conda install using python 3.8
> BUG: Updated installation instructions for numpy version restriction

- CHANGELOG.md
- docs/installation.rst
- pysat/_instrument.py
- pysat/tests/test_utils.py
Addresses #559 
Time/Epoch dimension for pysat produced netcdf4 files using `to_netCDF4` is now set to unlimited.
Unit test suite.
> Unlimited time dimension

- docs/requirements.txt
Read the docs is failing to build on develop since #525 was merged.  `portalocker` needs to be added to the requirements in the docs too.
```
ModuleNotFoundError: No module named 'portalocker'
```
Testing through compilation on readthedocs
> MAINT: update requirements for readthedocs

- CHANGELOG.md
- docs/new_instrument.rst
- docs/tutorial_basics.rst
- pysat/_files.py
- pysat/_instrument.py
- pysat/tests/test_files.py
- pysat/utils/files.py
Addresses roadmap, #566 (partial)
Some data products (including those from GOLD) use a cycle keyword in addition to version / revision to track files.  This adds support for this in the pysat files methods.  This is required before pysat/pysatNASA#7 can be merged.
Note this addresses the immediate requirement behind #566 so development can proceed, but the bug documented there should still be addressed, even though it currently does not affect instruments in development.
Unrelated issues with test_files.py documented in #597.  Will be updated in a future pull.
Using the branch at pysat/pysatNASA#7:
```
import pysat
nmax = …
```
> ENH: cycle keyword for files

- .travis.yml
- docs/api.rst
- docs/citing.rst
- docs/dependency.rst
- docs/new_instrument.rst
- docs/tutorial_basics.rst
- pysat/utils/coords.py
- pysat/utils/registry.py
- pysat/utils/time.py
- Updates broken links in docs
- Removed the "allow failures" for doc testing in Travis CI.
Tested locally via
```
sphinx-build -E -b html docs dist/docs
sphinx-build -b linkcheck docs dist/docs
```
* Mac OS X 10.15.7
* Python 3.8.2
* Sphinx 3.2.1
> DOC: broken links in sphinx build

- CHANGELOG.md
- pysat/tests/test_files.py
- pysat/tests/test_utils_files.py
Addresses #597, #565 (partial)
- Reduces code duplication in unit tests through classes
- Use `tempfile.tempdir.cleanup()` rather than manually deleting files created during tests
- Moves tests for migrated file utilities to test_utils_files.py
- Adds and improves docstrings, comments, test names
- Testing fix (non-breaking change which fixes an issue)
via pytest
> TST: update test_files.py structure

- CHANGELOG.md
- CONTRIBUTING.md
- pysat/_files.py
- pysat/_instrument.py
- pysat/instruments/methods/testing.py
- pysat/instruments/pysat_testing_xarray.py
- pysat/tests/test_instrument.py
- pysat/utils/files.py
As discussed in #604 and #611 it is too time intensive to define timezones to all timestamps.  However, we should not accidentally treat data from other timezones as UTC.  This PR addresses #514 by:
1) using `utcnow` for today/yesterday/tomorrow,
2) using Instrument time filtering function to convert times with timezones to UTC and then converting them to naive objects in UTC time, and
3) changing pds.DateOffset to dt.timedelta when appropriate.
Added a new unit test.  Also did a time analysis of pandas vs datetime incrementation:
```
import timeit
timeit.timeit("import datetime as dt; import pandas as pds; dt.datetime.utcnow() + …
```
> Added soft UTC testing

- pysat/instruments/methods/testing.py
- pysat/instruments/pysat_testing.py
- pysat/tests/instrument_test_class.py
- pysat/tests/test_instruments.py
- pysat/utils/_core.py
Addresses #573 
Moves user / password support from hardwired within tests to class structure to better support subpackages.  Leaving as draft until this is tested with pysatMadrigal.  Pinging @aburrell for further discussion and testing.  Syntax is based on the pysat 2.x implementation, but improvement suggestions are welcome.
Ran the unit tests with the `user_info` dictionary and without to validate tests continue to run as expected.
* Mac OS X 10.15.7
* Python 3.8.2
> TST: user support in instrument tests

- CHANGELOG.md
- docs/tutorial_iteration.rst
- pysat/_instrument.py
- pysat/_orbits.py
- pysat/instruments/methods/general.py
- pysat/instruments/methods/testing.py
- pysat/instruments/pysat_testing.py
- pysat/instruments/pysat_testing2d.py
- pysat/tests/test_custom.py
- pysat/tests/test_instrument.py
- pysat/tests/test_orbits.py
Replaces `pds.DateOffset` with `dt.timedelta` throughout.   The exceptions are where keywords of `months` or `years` are required, which are not supported by `timedelta`.  This was generated after the results of runtime tests from #622.  There is no significant difference in run time between this and the develop-3 branch, but putting this up as a draft for discussion.
This branch:  https://travis-ci.com/github/pysat/pysat/builds/207865614
develop3:  https://travis-ci.com/github/pysat/pysat/builds/207863988
The test `test_str_w_padding` in test_instrument's output was updated to reflect the change from pandas.
Tested via pytest.
* Mac OS X 10.15.7
* Python 3.8.2
> STY: Use datetime.timedelta, not pandas.DateOffset

- CHANGELOG.md
- pysat/_constellation.py
- pysat/_instrument.py
- pysat/tests/test_constellation.py
- pysat/tests/test_custom.py
Updates the style of the Constellation class and addresses #539 by allowing multiple types of Instrument inputs.  This makes it easier for users to create custom Constellation objects.
Added unit tests to test_constellation and ran new and existing tests locally.
I believe that no downstream changes are necessary, because the Instrument repositories don't actually load constellations.  However, individuals code will break if using the old kwarg.
> Constellation restriction removal

- CHANGELOG.md
- docs/new_instrument.rst
- pysat/_instrument.py
- pysat/tests/test_instrument.py
Removes the `multi_file_day` kwarg, requiring that it be set as an instrument attribute.
Addresses (in whole or part) #389, #620, #512, #266 
Tested by running unit tests and loading dmsp data:
```
import pysat; import datetime as dt; import pysatMadrigal as py_mad
stime = dt.datetime(1998, 1, 1)
dmsp_f13.load(date=stime)
print(dmsp_f13)
```
Yields
```
pysat Instrument object
-----------------------
Platform: 'dmsp'
Name: 'ivm'
Tag: 'utd'
Instrument id: 'f13'
Data Processing
---------------
Cleaning Level: 'clean'
Data Padding: None
Keyword Arguments Passed to load: {'xarray_coords': [], 'file_type': …
```
> Multiple file day attribute reorganization

- pysat/_instrument.py
- pysat/instruments/methods/testing.py
- pysat/tests/instrument_test_class.py
Addresses pysat/pysatMadrigal#5
Currently, user and password are not supported by the `remote_file_list` and `remote_date_range` methods.  This updates the syntax to pass all kwargs through both routines.
Additionally, updates the test class to pass these through for packages like pysatMadrigal.
Tested with the `tst/remote_file_list` branch of pysatMadrigal.  See pysat/pysatMadrigal#38.  Currently works with most of the methods there, but requires some bug fixes to some of the jro_isr data products.
```
import pysat
import pysatMadrigal as py_mad
dmsp_f13 = pysat.Instrument(inst_module=py_mad.instruments.dmsp_ivm, tag='utd', inst_id='f13')
dl_dict = {'user': 'your name here', 'password': 'email address'} …
```
> BUG/TST: support user and password kwargs in remote_file_list

- CHANGELOG.md
- pysat/_instrument.py
- pysat/tests/test_instrument.py
Addresses #471
- Fixes a bug when attempting to set data by indices for a multi-dimensional xarray object. 
- Includes `pysat_testing2d_xarray` as part of standard data tests.
- updated `test_setting_partial_data_by_*` tests with parametrize
Previous code assumes only epoch axis, and converts index values to timestamps.  However, if a secondary axis is used (Altitude in the case below), it will try to load altitude values as index values.  This bypasses the conversion and uses the integers directly as indices in this case.  This is the most flexible, as many types of dimensions can be used.
- Load Instrument
```
import pysat
inst = pysat.Instrument(inst_module=pysatNASA.instruments.icon_mighti, …
```
> BUG: xarray data access

- CHANGELOG.md
- docs/dependency.rst
- docs/new_instrument.rst
- docs/tutorial_custom.rst
- docs/tutorial_independence.rst
- pysat/_constellation.py
- pysat/_instrument.py
- pysat/tests/test_constellation.py
- pysat/tests/test_custom.py
Removes the `kind` kwarg from custom functions, addressing issue #635 and partially addresses #528.
Created new and adapted existing unit tests.  Check out `test_custom.py` for examples.
> Custom kind removal

- CHANGELOG.md
- pysat/_instrument.py
Fixed time specification if start but not stop provided.
This was tested by running the example code in pysatMadrigal:
```
import pysat
import pysatMadrigal as py_mad
stime = dt.datetime(2014, 12, 31)
ivm = pysat.Instrument(inst_module=py_mad.instruments.dmsp_ivm, tag='utd', inst_id='f15', update_files=True)
ivm.download(start=stime, user="Name+Surname", password="your@email.com")
ivm.files.files[stime]
'dms_ut_20141231_15.002.hdf5'
```
> BUG: fixed time assignment with start only

- pysat/instruments/methods/nasa_cdaweb.py
- pysat/tests/test_methods_cdaweb.py
Added deprecation warnings for CDAWEB methods.  Addresses #699 
Added unit tests for new deprecation warnings
> Deprecated cdaweb methods

- CHANGELOG.md
- pysat/_instrument.py
- pysat/tests/test_instrument.py
Added deprecation warnings to metadata labels attached to the Instrument object.  Addresses #679.
Added unit tests
> Deprecation warning for `Instrument.x_labels`

- CHANGELOG.md
- pysat/_instrument.py
- pysat/tests/test_instrument.py
Deprecated `sat_id` and allowed use of new `inst_id`, addresses #698.
Added unit test
> Deprecation warning for `sat_id`

- CHANGELOG.md
- pysat/_constellation.py
- pysat/tests/test_constellation.py
Added a deprecation warning for the old Constellation kwarg `name`, which has been replaced with `const_module`. Addresses #680.
Added a unit test for the new deprecation warning
> Deprecation warning to Constellation kwarg `name`

- CHANGELOG.md
- pysat/_instrument.py
- pysat/tests/test_instrument.py
Added a deprecation warning for Instruments that have a `default` method.  Addresses #684.
Added a unit test
> Deprecation warning for default Instrument method

- pysat/tests/test_utils_coords.py
- pysat/tests/test_utils_time.py
- pysat/utils/coords.py
- pysat/utils/time.py
Addresses #692 and #693
Updates message content, docstrings, and test standards for deprecation warnings in `utils.time` and `utils.coords`.
Existing unit tests, but standardized
> Deprecation warning improvement

- CHANGELOG.md
- pysat/_files.py
- pysat/tests/test_files.py
Addresses #700
The functions under `Files` that do not operate on the class have been moved to `utils.files`.  This updates the warnings and docstrings with info for users to warn them of this change.
Added unit tests for these functions
> Deprecation warning for functions in `Files` class

- CHANGELOG.md
- pysat/tests/test_utils_coords.py
- pysat/utils/coords.py
Fixes an error with the SLT calculation method, which only worked for pandas or xarray data that only has coordinates in the time dimension.
Created new unit tests, and ran in a local (complicated) function that originally revealed this error.
- [N/A] Make sure you are merging into the ``develop`` (not ``main``) branch
> BUG: SLT calculation with xarray instruments

- CHANGELOG.md
- pysat/_instrument.py
- pysat/tests/test_instrument.py
Added deprecation warnings for Instrument kwargs removed in pysat 3.0. Addresses #678.
Added a new unit test.
> Deprecation warnings for Instrument kwargs removed in pysat 3.0

- CHANGELOG.md
- pysat/instruments/dmsp_ivm.py
- pysat/instruments/jro_isr.py
- pysat/instruments/methods/madrigal.py
- pysat/tests/test_instruments.py
Added deprecation warnings to Madrigal instruments, routines, and methods.  Partially addresses #697 
Added a unit test for presence of a deprecation warning in an instrument module.  Did not add deprecation warnings for untested routines or methods.
> Deprecated Madrigal instruments and methods

- pysat/__init__.py
Addresses # 716
Change ensures that all needed internal .pysat directories are created if an existing v2 user updates without removing the existing .pysat directory.
Local test.
> ENH: Improved robustness of upgrade for v2 users

- CHANGELOG.md
- pysat/instruments/methods/sw.py
- pysat/instruments/sw_dst.py
- pysat/instruments/sw_f107.py
- pysat/instruments/sw_kp.py
- pysat/tests/test_instruments.py
- pysat/tests/test_sw.py
Deprecated the pysatSpaceWeather instruments and methods.  Partially addresses #697 .
Added new unit tests
> Dep2 spaceweather

- CHANGELOG.md
- pysat/instruments/ucar_tiegcm.py
- pysat/tests/test_instruments.py
Deprecated the pysatModels instrument.  Partially addresses #697.
Added new unit test.
> DEP: pysatModels Instruments

- CHANGELOG.md
- pysat/instruments/cosmic_gps.py
- pysat/tests/test_instruments.py
Partially addresses #697 by deprecating COSMIC GPS
Added more unit tests
> DEP: CDAAC instruments

- .travis.yml
- CHANGELOG.md
- docs/quickstart.rst
- docs/tutorial/tutorial_v3_upgrade.rst
- pysat/_params.py
- pysat/tests/test_params.py
- pysat/utils/files.py
Addresses #720 
Creates path provided to pysat.params['data_dirs'] rather than produce an error. Adds a basic valid path check to `pysat.utils.files.check_and_make_path`
Unit tests
> Data dirs user experience

- CHANGELOG.md
- pysat/constellations/test_diff_same.py
- pysat/constellations/test_diff_similar.py
- pysat/instruments/methods/testing.py
- pysat/instruments/pysat_testing.py
- pysat/instruments/pysat_testing2d.py
- pysat/instruments/pysat_testing2d_xarray.py
- pysat/instruments/pysat_testing_xarray.py
- pysat/instruments/pysat_testmodel.py
- pysat/tests/test_constellation.py
- pysat/tests/test_instrument.py
- pysat/tests/test_instruments.py
- pysat/tests/test_methods_general.py
- pysat/tests/test_omni_hro.py
- pysat/tests/test_utils.py
Addresses #686
Complements #735.  Moves those warnings here as part of 2.3.0.
I've included notes in the docs throughout the instruments for usage.  Let me know if these should be done differently.
testing via travis CI
> DEP: use of numeric sat_id to specify number of points

- CHANGELOG.md
- pysat/_instrument.py
Addresses #741 
Numpy dtypes are not direct instances of `np.dtype` starting with numpy 1.20.0.  This requires a change from using `type` to `isinstance` for type detection.
Locally, install numpy 1.20.  Running 
```
pytest pysat/tests/test_meta.py::TestBasics::test_nan_metadata_filtered_netcdf4_via_method
```
will detect if the routine runs correctly.  Likewise, any of the failing routines mentioned in #741.
* Mac OS X 10.15
* python 3.7.3
* numpy 1.20.1 and numpy 1.19.2
> BUG: numpy 1.20 compatibility

- CHANGELOG.md
- setup.py
Addresses #730
Changes in numpy 1.20 have resulted in some incompatibilities with the supported pandas version for pysat 2.x.  Since there is no cap in pandas 0.24 (the latest supported version here), we need to add a version cap to prevent faulty setups for the final deprecated version.
via local installs with different numpy setups.
> MAINT/BUG: numpy version cap needed for pysat 2.x

- CHANGELOG.md
- pysat/_instrument.py
Addresses #737, #738, #740
- Updated usage of `pds.index.to_native_types()` to `pds.index.astype(str)`
for pandas 2.0 compatibility (#737)
- Check type as `float` rather than `np.float` for future numpy compatibility
(#740)
- Verified usage of inst.loc[slice, keyword] will continue to work in
pandas 2.0 (#738)
- Maintenance fix (non-breaking change which fixes an issue)
Ran unit tests tested locally with
* python 3.8.2
* numpy 1.20.1
* pandas 1.2.3
* xarray 0.17.0
* netCDF4 1.5.6
Note that there are some deprecation warnings were originating from the usage of numpy in netCDF4, these issues were updated in the 1.5.6 release.
> MAINT: future numpy and pandas standards

- CHANGELOG.md
- docs/new_instrument.rst
- pysat/_files.py
- pysat/_instrument.py
- pysat/_orbits.py
- pysat/instruments/methods/testing.py
- pysat/instruments/pysat_testing.py
- pysat/instruments/pysat_testing2d.py
- pysat/instruments/pysat_testing2d_xarray.py
- pysat/instruments/pysat_testing_xarray.py
- pysat/instruments/pysat_testmodel.py
- pysat/tests/test_files.py
- pysat/tests/test_instrument.py
- pysat/tests/test_orbits.py
- pysat/tests/test_utils_coords.py
- pysat/utils/coords.py
Addresses SLT upgrade request in #723, bug in #728, and more!
- Adds support to disable constraining SLT values to [0, 24). Variable is continuous when loading multiple days.
-  Fixes .copy(). Extends .copy() and __eq__ across Instrument classes. Tests added. 
- Tests with __repr__()
- Expands general Instrument tests to Instruments instantiated via `inst_module`
- Condenses methods used by pysat testing instruments. Adds support for keyword tests to all.
- I would appreciate feedback on formatting support function docstrings in testing.py
- Updates the initialization keyword argument process. 
- Always an entry for each Instrument function.
- 'partial' function keywords retained;  eval(__repr__()) would otherwise lose those keywords
- Switch all keyword treatment over to 'partial'. All …
> ENH/BUG: Add No Modulus Option to SLT Calculations, .copy() Fix, and More!

- CHANGELOG.md
- pysat/_instrument.py
- pysat/tests/test_instrument.py
I turned the last review comment over in #727 into its own pull for clarity and/or to make it easy to push to v3.0.1.
Changes in keyword assignment in the other pull made the internal division between python functions and functools.partial unnecessary. That code was reduced but not completely. This pull removes lines no longer needed.
Ramifications of this change:
- In current develop branch, some instrument support module functions that are attached to a pysat.Instrument object are always going to be `functools.partial`, independent of what the developer provides. This depends on the support function. Other functions will stay as a natural python function or functools.partial.
- In this pull, all support functions remain the same type as provided by the developer
- …
> STY: Condense keyword assignment code

- CHANGELOG.md
- docs/new_instrument.rst
- pysat/instruments/methods/general.py
- pysat/tests/test_methods_general.py
I created a general method for loading multiple CSV files into a DataSet.  This currently is introduced in pysatSpaceWeather, but should probably be here. https://github.com/pysat/pysatSpaceWeather/pull/48
Introduced new unit tests.  Also used to load pysatSpaceWeather ACE data.  See example in linked PR above.
* Version number: Python 3.7
* Any details about your local setup that are relevant: method pulled from pysatSpaceWeather branch https://github.com/pysat/pysatSpaceWeather/pull/48
checklist …
> Added a general load routine for CSV files

- CHANGELOG.md
- pysat/tests/test_utils_files.py
Addresses #782
Updates unit tests to use new instrument names in pysatSpaceWeather.
Tested via Github Actions
> MAINT: pysatSpaceWeather compatibility

- CHANGELOG.md
- pysat/_instrument.py
- pysat/tests/test_files.py
- pysat/tests/test_instrument.py
Addresses #784, #537
Adds a check if the user supplied `tag` and `inst_id` are actually supported by the requested instrument support module.
- Added a test, with error message check, when an invalid tag or inst_id provided
* Operating system: MacOS 10.15.4
* Version number: Python 3.7 …
> ENH/BUG: inst_id and tag check

- CONTRIBUTING.md
- docs/new_instrument.rst
- pysat/__init__.py
- pysat/tests/ci_test_class.py
- pysat/tests/test_files.py
- pysat/tests/test_params.py
- pysat/tests/test_utils_files.py
Addresses #777 
- Removes hardwired code that automatically sets the data directory on Travis.  This is now set outside the code depending on CI environment
- Scrubs docstrings for mentions of Travis to generalize to CI
- Maintenance fix (non-breaking change which fixes an issue)
Tested via Github Actions 
> MAINT: Update refs to Travis CI

- CHANGELOG.md
- pysat/_instrument.py
- pysat/tests/test_instrument.py
You can enter time information into download that result in an empty date array.  This can cause uninformative errors to be raised in Instrument download routines and hide a possible user error.  This PR fixes that by warning the user that no downloads were attempted for the specified date range.
Added a unit test.  Also:
```
import pysat
inst = pysat.Instrument('your', 'fav', 'inst', 'here')
inst.download(dt.datetime(2009, 1, 1), dt.datetime(2008, 1, 1))
```
* Any details about your local setup that are relevant: found using pysatSpaceWeather Prelim F10.7 data.
If this is a release PR, …
> Download calls that create an empty date array

- pysat/_instrument.py
- pysat/tests/test_instrument.py
Addresses issue raised in comments to the last direct develop commit 🙈 
Created a new unit test for loading data with custom kwargs that can now be supplied either on instantiation or during the load call.  If a load call kwarg is the same as an instantiation kwarg, the load call one will take precidence.
> Load kwarg tests

- .github/workflows/main.yml
Addresses #817 
Somewhere in the primordial windows test branch, coveralls tests were removed during debugging.  This restores them to the develop branch.
Looking at the results on coveralls:
https://coveralls.io/github/pysat/pysat?branch=bug/coveralls
> BUG: restore coveralls

- CHANGELOG.md
- pysat/_constellation.py
- pysat/tests/test_constellation.py
Added an `empty_partial` flag to the Constellation class, addresses #800.
Updated unit tests
> Added  `empty_partial` property to the Constellation class

- requirements.txt
Addresses #824
Introduces version limit on netCDF given changes in windows version.
Testing in progress via GitHub Actions.
* Operating system: GitHub Actions
* Version number: Python 3.8, 3.9
> netCDF version limit 

- .github/workflows/main.yml
- CHANGELOG.md
- pysat/tests/test_utils.py
- pysat/utils/_core.py
- requirements.txt
Addresses #830
Improves code coverage of `listify`. Now works on empty lists.
- Expanded range of inputs of existing tests to include `[]` and `[[]]` inputs.
> BUG: Added code for missing listify input of []

- CHANGELOG.md
- pysat/tests/test_instrument.py
- requirements.txt
Addresses #833
Improves usage of pandas in unit tests to better comply with updates in pandas 1.3.0
via pytest
* pandas 1.3.0, numpy 1.21.0
> BUG/STY: pandas 1.3.0 compliance

- CHANGELOG.md
- pysat/utils/_core.py
Addresses #847 by using the `MetaLabel` defaults.
Running unit tests and loading a netCDF file locally:
```
import pysat
fnames = ["your file"]
pandas_format = False  # Or True if it is only a time-dimension data file
data, meta = pysat.utils.load_netcdf4(fnames, pandas_format=pandas_format)
print(meta.labels)
MetaLabels:
-----------
units->units       name->long_name    notes->notes       
desc->desc         min_val->value_min max_val->value_max 
fill_val->fill
```
Previously, 'axis', 'scale', and 'plot' were also present.
If this is a release PR, …
> Fixed default `load_netcdf4` labels

- CHANGELOG.md
- docs/tutorial/tutorial_basics.rst
- pysat/_instrument.py
- pysat/tests/instrument_test_class.py
- pysat/tests/test_instrument.py
This pull request changes the `_assign_attrs` method to define the `inst_module` attribute consistently for all instantiation methods.  This fully addresses #324.  I also:
- Added a paragraph to the docs describing how to use `help` to access the Instrument sub-module information.
- Fixed the `tag` and `inst_id` defaults to reflect the docstring definition and removed the extra logic needed when the old defaults were used.
```
import pysat
cindi = pysat.Instrument(platform='cnofs', name='ivm')
cindi.inst_module
<module 'pysatNASA.instruments.cnofs_ivm' from '~/Git/pysatNASA/pysatNASA/instruments/cnofs_ivm.py'>
```
**Test …
> Defining `inst_module` the same regardless of instantiation method

- CHANGELOG.md
- pysat/tests/test_meta.py
- pysat/tests/test_orbits.py
Addresses #545, partial updates to #565 and #860
- Adds missing docstrings to unit tests for `test_meta`
- Removed duplicate test
- Renames several tests for clarity
- Improves docstring style for future compliance with #860
Note that many tests could be optimized or combined, this is out of scope here in the light of planned changes to metadata (ie, #767, #786, #789)
Using flake8-docstrings.
```
flake8 . --count --select=D,E,F,W --statistics
```
* Version number: Python 3.8.3 …
> DOC/STY: Update Docstrings in test_meta

- pysat/instruments/__init__.py
- pysat/instruments/methods/__init__.py
- pysat/instruments/methods/general.py
- pysat/instruments/methods/testing.py
- pysat/instruments/pysat_testing.py
- pysat/instruments/pysat_testing2d.py
- pysat/instruments/pysat_testing2d_xarray.py
- pysat/instruments/pysat_testing_xarray.py
- pysat/instruments/pysat_testmodel.py
- pysat/instruments/templates/__init__.py
- pysat/instruments/templates/template_instrument.py
- pysat/tests/test_instruments.py
Addresses #860 (partial).
Scrubs docstrings in test instruments and improves usage of returns.
With `flake8-docstrings` installed:
```
flake8 --select=D,E,F,W --count --statistics
```
* flake8, flake8-docstrings
> STY: docstrings -- test instruments

- CHANGELOG.md
- pysat/tests/test_files.py
- pysat/tests/test_meta.py
- pysat/tests/test_utils.py
- pysat/tests/test_utils_coords.py
- pysat/tests/test_utils_testing.py
- pysat/tests/test_utils_time.py
- pysat/utils/__init__.py
Addresses #860
Updates a few styles from previous pulls now that `hacking` may be incorporated alongside `flake8-docstrings`.  Changes include 
- "new style" declaration of classes (inherit from object)
- Tightening up one-line docstrings
- import order
- Include more info on TODO comments
For each modified file
```
flake8 --select=D,H --count --statistics ./pysat/tests/test_utils_testing.py
```
* Requires: `flake8`, `flake8-docstrings`, `hacking` …
> STY: cleanup previous pulls in flake8 chain

- CHANGELOG.md
- pysat/_instrument.py
- pysat/tests/test_instrument.py
Addresses the 3.1.0 Milestone portion of #788 by adding a deprecation warning to the download `freq` kwarg.
Added a unit test.
- [n/a] My changes generate no new warnings
> Add deprecation warning for download kwarg ,`freq`

- CHANGELOG.md
- pysat/instruments/methods/testing.py
- pysat/instruments/pysat_testing.py
- pysat/instruments/pysat_testing2d.py
- pysat/instruments/pysat_testing2d_xarray.py
- pysat/instruments/pysat_testing_xarray.py
- pysat/instruments/pysat_testmodel.py
- pysat/tests/test_instruments.py
- pysat/tests/test_methods_testing.py
Addresses #389 (partial) and #621
Moves the metadata for the test instruments to a single location.  All possible values are generated, but only the values required are passed through to the instrument.  Expanded some values of metadata to include min and max values.
Adds `start_time` to the test instruments as an optional kwarg.  If specified, the start time will be adjusted by the specified offset (as a `dt.timedelta`).
- Includes unit tests for the changes to `generate_times` as part of new test_methods_testing.py file.
- Includes integration tests for each test instrument to ensure both `start_time` and `num_samples` are passed through correctly.
- Note that end time is not tested in the integration tests since each instrument has a different hard-wired frequency.  However, this is …
> STY/ENH: Testing Instruments -- metadata and start_time

- CHANGELOG.md
- pysat/tests/test_instruments.py
Addresses #631
I missed that this kwarg was added in a previous pull, solving the issue.  Adding an integration test to test the incorporation into the test instruments.
via pyest
* Operating system: Mac 10.15.7
> TST: add integration test for `file_date_range`

- CHANGELOG.md
- pysat/tests/test_constellation.py
- pysat/tests/test_custom.py
- pysat/tests/test_utils.py
Addresses #751
Streamlines unit tests involving standard and logger output
- Uses `capsys` in unit tests to capture standard output to terminal for tests.  
- Uses `caplog` to capture standard logger output at a given level.
- Style feature (non-breaking change which adds functionality)
via pytest
> STY: usage of caplog and capsys in unit tests

- pysat/_instrument.py
- pysat/tests/test_instrument.py
Addresses #860 (partial), #565 (partial), #532 (partial)
Adds new style and docstring requirements to test_instrument.py.  Since this file is huge (#870), I've broken the changes into three pulls covering roughly 1000 lines of code each.
Some use of parametrize to simplify, but holding off on a full sweep of duplicate tests for a future pull.
via pytest, and via
```
flake8 --select=D,H --count --statistics pysat/tests/*
```
At this point in the queue, the first flake8 violation should occur in line 2193 in test_instrument.py
* Operating system: Mac 10.15.7
* `flake8`, `flake8-docstrings`, `hacking`
If this is a release PR, replace the …
> DOC/STY: docstrings and style in test_instrument (B) (8 of 11) 

- pysat/tests/test_instrument.py
Final unit test sweep!
Addresses #860 (partial), #565 (closes)
Adds new style and docstring requirements to test_instrument.py.  Since this file is huge (#870), I've broken the changes into three pulls covering roughly 1000 lines of code each.
via pytest, and via
```
flake8 --select=D,H --count --statistics pysat/tests/*
```
At this point in the queue, there should be no violations in the test files.
* Operating system: Mac 10.15.7
* `flake8`, `flake8-docstrings`, `hacking` …
> DOC/STY: docstrings and style in test_instrument (C) (9 of 11)

- CHANGELOG.md
- pysat/instruments/templates/template_instrument.py
- pysat/tests/test_utils.py
- pysat/utils/_core.py
Addresses #823
Starting in `xarray` 0.16, loading from netcdf checks for time-like units and automatically converts the data into `dt.timedelta`s.  Adding the `decode_timedelta=False` kwarg to the load statements to maintain data format as default, but users may create instruments that pass this kwarg through if desired.
Updates the instrument template with default behavior for xarray and how to modify.
Note: The unit tests in this class will be rewritten as part of #60.  The current writeup is a workaround for the inability to write to netcdf4 directly from pysat.
New unit test captures behavior.
* …
> BUG/ENH: decode_timedelta for loading into xarray

- CHANGELOG.md
- pysat/utils/_core.py
Addresses #887
On some windows systems, xarray leaves a link to the file open, which can create problems in the unit test suite.  This closes the file after loading the data.
via pytest on windows
> BUG: close files through xarray

- CHANGELOG.md
- pysat/tests/test_instrument.py
- pysat/tests/test_utils_time.py
Addresses #532 
Reduces duplicate code in test_instrument.
- Incorporates pytest.mark.parametrize
- Applies common evaluation functions
- Use class-level setup and teardown instead of global declarations
- Moves `test_filter_datetime` to test_utils_time.py since this does not require an instrument to be initialized. Deletes several existing tests there since this version repeats those but more comprehensively.
Via pytest.
> STY: reduce code duplication in test_instrument (1 of 2)

- CHANGELOG.md
- docs/new_instrument.rst
- pysat/_instrument.py
- pysat/instruments/templates/template_instrument.py
- pysat/tests/test_instrument.py
- pysat/utils/_core.py
Addresses #807
- Deprecates `_test_download_travis` attribute and replaces it with `_test_download_ci`.  
- Adds test for deprecation warnings
- Adds unit test for setting the custom test attrs (`_test_download`, `_test_download_ci`, and `_password_req`) via the instrument module.
Tested via pytest.
> DEP/TST: deprecation of `_test_download_travis`, test setting of instrument test attrs

- pysat/tests/test_instrument.py
Addresses #532
- Added options to evaluation functions to improve utility across the unit tests.
- Consistent use of `reverse` kwarg in functions to improve parametrize usage.
- Regrouped multiple functions under @pytest.mark.parametrize
- Minor style changes for consistency
- Removed a duplicate test missed in #890.
Via `pytest -vs pysat/tests/test_instrument.py::TestBasics` to compare number of tests run before and after changes
- [na] Add a note to ``CHANGELOG.md``, summarizing the changes -- Changes fall under #890 changelog …
> STY: reduce code duplication in test_instrument (2 of 2?)

- CHANGELOG.md
- pysat/_instrument.py
- pysat/tests/test_instrument.py
Addresses #892
If `tag` or `inst_id` are specified as None, allow these to pass through as an empty string.
EDIT: These were removed prematurely from develop.  verified that this functionality is still present in v3.0.1:
https://github.com/pysat/pysat/blob/4d12a09ea585b88d54560413e03cae9289113718/pysat/_instrument.py#L221-L223
This pull restores the functionality but adds a DeprecationWarning and appropriate tests.
```
import pysat
test = pysat.Instrument('pysat', 'testing', tag=None)
test = pysat.Instrument('pysat', 'testing', inst_id=None)
```
Both should instantiate successfully.
If this is a release PR, replace the first item of the above …
> BUG: Allow `tag` and `inst_id` to be None, add Deprecation

- CHANGELOG.md
- pysat/tests/test_utils_time.py
- pysat/utils/time.py
Addresses #906
Currently, `pysat.utils.time.create_datetime_index` assumes all incoming dates are in sequential order.  Depending on the user system, this is not always the case.  This rewrites the code to convert incoming values as `timedelta64` objects.
Testing the function:
```
import pysat
year = np.array([2014, 2014, 2008])
day = np.array([1, 2, 365])
uts = np.array([0, 3600, 2700])
pysat.utils.time.create_datetime_index(year=year, day=day, uts=uts)
```
The resulting datetime index should match expectations based on the inputs. …
> BUG: assumptions in `create_datetime_index`

- CHANGELOG.md
- pysat/_instrument.py
- pysat/tests/classes/cls_instrument_property.py
Addresses #850
If a user supplies both `inst_module` and `platform`/`name`, `pysat` will default to `inst_module` during instantiation.  This pull maintains that behaviour, but adds a warning so the user knows what is happening.  Warning is through if `platform` or `name` supplied just in case.
```
import pysat
inst = pysat.Instrument('cnofs', 'ivm', inst_module=pysatNASA.instruments.cnofs_vefi, tag='dc_b')
```
Look for warning message.
> BUG: warn users when instantiated via `inst_module` AND `platform`/`name`

- CHANGELOG.md
- docs/dependency.rst
- pysat/instruments/pysat_testing.py
- pysat/tests/classes/cls_instrument_library.py
- pysat/utils/_core.py
- setup.cfg
Addresses #583
Modifies the instrument identification so that instruments may pass through a series of optional kwargs for `test_load`. The optional kwargs may be passed through as a dict or list of dicts describing each configuration.  Note that this only verifies that the data can be successfully loaded under this configuration, custom tests are required for testing specific outcomes.
Backwards-compatible with develop.  A new pytest mark is added (load_options).  Note that if this is unregistered in setup.cfg of downstream packages, the tests will still run and a warning will be generated asking the user to register the new mark.
Testing with local tests of pysat/pysatNASA#91. 
``` …
```
> TST: add the ability to pass kwargs through standard load tests

- CHANGELOG.md
- docs/instruments/pysatMadrigal.rst
- docs/tutorial/tutorial_basics.rst
- pysat/_instrument.py
- pysat/_meta.py
- pysat/tests/classes/cls_instrument_access.py
- pysat/tests/test_meta.py
- pysat/tests/test_utils.py
- pysat/utils/__init__.py
- pysat/utils/_core.py
Addresses #900 by using Meta rename in Instrument rename.  Also updated Instrument rename to allow a function as mapping input alongside the dictionary input.  Fixed a bug in Meta rename to use the same style of dict input as Instrument (necessary for higher order data).
Added new unit tests, running old unit tests, and added examples to the Instrument.rename docstring. …
> Updated Instrument rename method

- CHANGELOG.md
- pysat/_constellation.py
- pysat/tests/test_constellation.py
Addresses #842 and reduces duplicate code lines by adding a hidden Constellation method to iteratively call Instrument methods.
Added a unit test and called existing unit tests.
* Operating system: OSX Mojave
> Added `_call_inst_method` to Constellation

- CHANGELOG.md
- pysat/tests/test_utils.py
- pysat/utils/_core.py
Fixes a bug found when trying to scale 'n/cc' or '/cc'.
Added unit tests.  Also:
```
import pytest
pysat.utils.scale_units('n/cc', 'cm-3')
1.0
```
> Scale units bugfix

- CHANGELOG.md
- pysat/tests/test_utils_io.py
- pysat/tests/test_utils_testing.py
- pysat/utils/testing.py
- test_requirements.txt
Moved `prep_dir` to testing utils, as it will be useful for unit tests in pysatMadrigal.
- New feature (non-breaking change which adds functionality
Ran new and existing unit tests.
> Moved `prep_dir` to testing utils

- CHANGELOG.md
- pysat/_meta.py
- pysat/tests/test_meta.py
- test_requirements.txt
If a user supplies an array to metadata as part of an instrument, pysat will warn them. However, the warning currently gives them the wrong key as feedback, meaning every warning says that 'Var_Type' is the problem key even if it has done nothing wrong. 😿 
This provides the correct key as well as the variable name to aid in debugging problems. 
Additionally, this imposes a version on coveralls to keep breaking changes there from affecting the continuous integration.
Follow instructions in pysat/pysatNASA#99 to see the feedback.  Or, in a simpler fashion
```
import pysat
meta = pysat.Meta()
meta['new_var'] = {'valid_range': [-100, 100]}
```
If …
> MAINT/BUG: meta warnings for arrays

- CHANGELOG.md
- pysat/tests/test_utils.py
- pysat/utils/_core.py
- test_requirements.txt
Listify cannot handle dict_keys or dict_values as input.  Added a note to the docstring and a unit test to ensure it is incorrectly handled in the expected fashion.  Technically fixes this bug by descoping the routine.
Added new unit test
> Clarified `listify` limitations

- CHANGELOG.md
- pysat/instruments/pysat_testing.py
- pysat/instruments/pysat_testing2d.py
- pysat/instruments/pysat_testing2d_xarray.py
- pysat/instruments/pysat_testing_xarray.py
- pysat/tests/test_instruments.py
Addresses https://github.com/pysat/pysatModels/pull/96
Been working on adding unit tests for pysatModels and the irregular interpolation function. Ran into an issue driven by the starting latitude (90 degrees) of pysat test instruments. Added a keyword argument `max_latitude` that defaults to 90.
- Unit tests developed in pysatModels
- Will check on what to do here.
If this is a …
> Expand pysat testing kwargs

- CHANGELOG.md
- pysat/tests/test_utils_io.py
- pysat/utils/_core.py
- pysat/utils/io.py
Addresses #944.  
Adds `epoch_unit` and `epoch_origin` to both `load_netCDF` functions.  Both kwargs follow the standards for `unit` and `origin` (respectively) as defined by `pandas.to_datetime`.
Test by loading a `cosmic2_ivm` instrument from pysat/pysatCDAAC#32, which uses a different origin (Jan 6, 1980) and units (s) than the defaults (Jan 1, 1970; ms).  The index of the instrument should match the date loaded.
* pysat/pysatCDAAC#32
> ENH: kwargs for epoch options

- CHANGELOG.md
- pysat/_meta.py
- pysat/tests/test_meta.py
- pysat/tests/test_meta_labels.py
- pysat/tests/test_utils_io.py
Updated the meta data assignment by checking type against expected label type, updating MetaLabels if needed, and *not* allowing array inputs.  Possibly addresses #940 and was meant to address https://github.com/pysat/pysatNASA/issues/99.
```
import pysat
test_inst = pysat.Instrument('pysat', 'testing')
test_inst.load(2009, 1)
test_inst.meta['dummy1'] = {'new meta': 'test string'}
test_inst.meta['dummy1'] = {'new meta': 'test string'}
test_inst.meta['dummy1'] = {'new meta': b'test bytes'}
test_inst.meta['dummy2'] = {'new_bytes': b'test bytes'}
test_inst.meta.labels.label_type
{'units': str,
'name': str,
'notes': str,
'desc': str, …
```
> ENH: updated meta assignment

- CHANGELOG.md
- pysat/instruments/pysat_testmodel.py
- pysat/tests/test_utils_coords.py
- pysat/utils/coords.py
When running a model validation period, I encountered the following error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-22-0f94a05e9ffd> in <module>
----> 1 (pairs, pairs_meta, inst_dat, mod_dat, inst_loc) = sami3_val.pair_sami3_inst(stime, etime, inst_name, mod_prefix,
2                                     user=user, password=password,
3                                     skip_download=skip_download,
4                                     mod_dir=mod_dir, data_dir=data_dir,
5                                     data_type=data_type, comp_clean=comp_clean)
~/Programs/Models/SAMI3/tools/sami3_validation_rout.py in pair_sami3_inst(stime, etime, inst_name, mod_prefix, …
```
> BUG: update_longitude assignment issue

- .github/workflows/main.yml
- CHANGELOG.md
- requirements.txt
- setup.cfg
Addresses #828.  May address #824 as far as CI testing is concerned.
Updates test versions according to NEP29: https://numpy.org/neps/nep-0029-deprecation_policy.html
- On Dec 22, 2021, support for numpy 1.18 can be dropped.
- On Dec 26, 2021, support for python 3.7 can be dropped.
- Adds support for python 3.10, released Oct 2021.
- Drops version cap on netCDF4 with release of v1.5.8, which fixes the windows issues encountered in pysat CI tests previously.  Included here for improved python 3.10 compliance.
- Fixed tab/space mixing in setup.cfg
via github actions
* Operating system: ubuntu, windows
* Version number: Python 3.8, 3.9, 3.10
* python 3.8 run with numpy 1.19
If this is a release PR, replace the first …
> MAINT: NEP29 dec2021 updates + netCDF4 cap removal

- CHANGELOG.md
- pysat/_instrument.py
- pysat/instruments/pysat_testing2d.py
- pysat/instruments/pysat_testing_xarray.py
- pysat/tests/test_instrument.py
- pysat/tests/test_instruments.py
- pysat/tests/test_meta.py
- pysat/utils/io.py
Addresses #908 (partial) and #913
After merge, bump milestones of issues rather than close.
- Adds a DeprecationWarning when a user attempts to set a data object for 2d data.
- Deprecates pandas2d instrument.
- Deprecates the 1d xarray instrument (redendant) in partial support of #908.
The deprecation of meta children (#789) will be handled in a separate pull.
- Warnings for upcoming Breaking change (fix or feature that would cause existing functionality
```
import pysat
import warnings
warnings.simplefilter("always", DeprecationWarning)
test = pysat.Instrument('pysat', 'testing2d')
test.load(2009, 1)
test['new_mlt'] = 2 * test['mlt']
test['new_profiles'] = 2 * test['profiles']
```
* Operating system: Mac OS X 11.6.1
* Version number: …
> DEP: DeprecationWarnings for 2d pandas data, pysat_testing2d and pysat_testing_xarray

- CHANGELOG.md
- pysat/tests/test_meta.py
pandas 1.4 throws some FutureWarnings which mess up the warning checks in test_meta.  This adjusts things so pysat does not assume the required UserWarnings are not necessarily the first warnings raised.
> BUG: warning check

- CHANGELOG.md
- pysat/_files.py
- pysat/tests/test_files.py
- pysat/tests/test_methods_general.py
Closes #976, #977, #978
Updates pandas standards in accordance with newly deprecated behaviour in pandas 1.4.0.  Deprecated pandas syntax will be removed in pandas 2.0.0.
tested via github actions.  Inspection of the logs shows that new FutureWarnings from pandas are suppressed (compare with develop).
> MAINT: pandas 1.4.0 deprecations

- CHANGELOG.md
- pysat/_meta.py
- pysat/tests/test_meta.py
- test_requirements.txt
Addresses #789 (milestone bump).  
Adds DeprecationWarning when new higher order metadata is set.
- Warning for upcoming Breaking change (fix or feature that would cause existing functionality
```
import pysat
import warnings
warnings.simplefilter("always", DeprecationWarning)
test = pysat.Instrument('pysat', 'testing2d')
test.load(2009, 1)
```
* Operating system: Mac OS X 11.6.1
* Version number: Python 3.9.9
> DEP: DeprecationWarning for higher order metadata

- CHANGELOG.md
- pysat/constellations/__init__.py
- pysat/instruments/__init__.py
Addresses #829
Deletes temporary variables invoked as part of certain init files.
via pytest, importing pysat and loading instruments.
* Operating system: Mac 11.6.3
> STY: remove temporary init variables

- CHANGELOG.md
- docs/new_instrument.rst
- pysat/_files.py
- pysat/instruments/templates/template_instrument.py
- pysat/tests/test_files.py
- pysat/utils/files.py
Addresses #763, #762
- Added support for user supplied variables in file template strings, not just those used for dates.
- Improved support for delimited filenames. More than one variable can be within a single delimited section. Delimited sections are not required to have a variable.
- Updated docstring in `from_os` as well as supporting methods. 
- Added tests for delimited filenames, user variables, and wildcard use.
- Condensed existing tests
- Output from `process_parsed_filenames` is now always sorted
instructions so we can reproduce. Please also list any …
> ENH: Improve file parsing

- pysat/tests/test_utils_coords.py
- pysat/utils/coords.py
Temporary bugfix for xarray coordinate updates.  This is a temporary fix to allow ecosystem packages to work as expected until #988 is fully addressed.
See Issue #988.
* Any details about your local setup that are relevant: develop branch of pysatMadrigal, pysatModels
> BUG: longitude update fix

- CHANGELOG.md
- pysat/instruments/methods/general.py
- pysat/instruments/pysat_testing2d.py
- pysat/tests/test_methods_general.py
- pysat/tests/test_utils_io.py
- pysat/utils/io.py
Addresses #947
The timestamp conversion for datasets loaded using `io.load_netcdf` is not consistently handled in pandas and xarray.  This fixes that issue so there are not separate workflows for data types.  Note that `io.inst_to_netcdf` still needs to be updated.  That is documented in #991.
Converts timestamps for `xarray` datasets in a manner similar to the conversion for `pandas` datasets.  Deprecates the function `instruments.methods.general.convert_timestamp_to_datetime` as this is used by some instruments outside of the core code to convert timestamps for xarray objects.
Note that if the deprecated function `convert_timestamp_to_datetime` is run on a variable already converted to datetime, it is now passed through unchanged.  This allows for backwards compatibility for outside …
> ENH/DEP: timestamp conversions for xarray

- pysat/_instrument.py
- pysat/instruments/methods/general.py
- pysat/instruments/pysat_testing2d.py
- pysat/instruments/pysat_testing_xarray.py
- pysat/tests/instrument_test_class.py
- pysat/utils/_core.py
Now that pysat 3.0.2 is next on the release schedule, this updates the documentation to show that existing deprecations were added there rather than the future 3.1.0.
using find all in atom.
* Operating system: Big Sur
> DOC: update deprecation info

- CHANGELOG.md
- docs/dependency.rst
Closes #965
Provides a quick summary of how to employ version checking in downstream packages, based on current implementation.
Based on implementation in pysatModels.
* Operating system: Big Sur
> DOC: version checking for packages that require new pysat features

- pysat/_constellation.py
- pysat/_instrument.py
- pysat/tests/classes/cls_instrument_access.py
- pysat/tests/classes/cls_instrument_library.py
- pysat/tests/classes/cls_instrument_property.py
- pysat/tests/test_constellation.py
- pysat/tests/test_files.py
- pysat/tests/test_instrument.py
- pysat/tests/test_instrument_custom.py
- pysat/tests/test_instrument_index.py
- pysat/tests/test_instrument_padding.py
- pysat/tests/test_instruments.py
- pysat/tests/test_meta.py
- pysat/tests/test_methods_general.py
- pysat/tests/test_methods_testing.py
- pysat/tests/test_orbits.py
- pysat/tests/test_utils_coords.py
- pysat/tests/test_utils_files.py
- pysat/tests/test_utils_io.py
Allow users to specify the `use_header` load option at initialization of an instrument instead of just when loading.
Clean up of this kwarg is now captured in #1020.
```
import pysat
cindi = pysat.Instrument('cnofs', 'ivm', use_header=True)
stime = dt.datetime(2009, 4, 10)
cindi.load(date=stime)
```
No deprecation warnings should appear.
> ENH: allow `use_header` setting at init

- pysat/tests/classes/cls_instrument_iteration.py
Based on a suggestion by @aburrell in #1014.  Part of earlier changelog description in this release.
```
* Reorganized tests for the `pysat.Instrument` class into multiple files
* Updated unit tests for `pysat.Instrument` with pytest.mark.parametrize
```
docstrings are copy / paste, suggestions welcome.
> STY: usage of bounds in iteration tests

- CHANGELOG.md
- pysat/_instrument.py
- requirements.txt
Addresses #1026
Pysat allows users to access data a number of ways.  The `getitem` functions in the `pysat.Instrument` class pass these through to pandas and xarray using try/except statements.  Error types are monitored to infer the appropriate syntax.
xarray 2022.06 updates the default error when inputting a slice incorrectly from `TypeError` to `ValueError`, breaking pysat's assumptions for how to alter the syntax.  This fixes the problem, and additionally cleans up and documents the logic.
Existing unit tests pass.  The bug would manifest in the existing tests.
Also tested with the develop branch of pysatNASA.
* Operating system: Mac OS X Big Sur
* xarray 2022.03 and xarray …
> BUG: Use of slices to access xarray data

- CHANGELOG.md
- pysat/instruments/methods/testing.py
- pysat/tests/test_methods_testing.py
Addresses #1036
`pysat.instruments.methods.testing.generate_times` currently does not work for high-frequency values (<1s).  The returned index is correct, but the `uts` will return only integer seconds.
This impacts other projects such as `pysatMissions` that use this function.
```
from pysat.instruments.methods import testing as ps_meth
uts, index, dates = ps_meth.generate_times(['2018-01-01.no_file'], 5400, freq='10mS')
```
Inspect `uts` and `index`. In develop, `uts` will be zero for all points, in this branch, it will have fractional values.
* Operating system: Mac OS X Big Sur
checklist on …
> BUG: fractional times for test instruments

- CHANGELOG.md
- pysat/utils/_core.py
Addresses #1039
This fixes a bug introduced in pysat 3.0.2 in the unit tests that are inherited by the ecosystem packages.  Downloads from FTP instruments are skipped in the CI environment, but run locally.  The bug mistakenly assigns the `no_download` suite of tests, which check for a warning message is downloads are not supported.
This is affecting the unit tests in pysatSpaceWeather since the release of pysat 3.0.2.  Recommend we add the fix into the RC and test a branch there against the new RC.
In pysat.utils._core.py, replace `(os.environ.get('CI') == 'true')` on line 470 with `(os.environ.get('CI') is None)` to simulate a True response while on a local system.  Then run:
```
import pysat
import pysatSpaceWeather
inst_list = …
```
> BUG: ci_skip

- .github/workflows/main.yml
- CHANGELOG.md
- pysat/_meta.py
Addresses #1044 
Addresses the change to 'None' assignment with pandas 1.5 by forcing the relevant column to a non-numeric state. This fix keeps None as None so no other changes by users or developers are needed. There may be a slightly more elegant solution, first I assign an empty string, then None. May be possible to do in one line but current fix appears effective.
- Ran test_meta locally. Using CI to check other versions.
* Operating system: Mac
* Version number: Python 3.10
* Installed today!
If …
> Change in children - bugfix 

- CHANGELOG.md
- pysat/_instrument.py
Closes #1032
Adds somedescription to the use of file_format in the docstring.
unit tests.
> BUG/DOC: file_format description

- CHANGELOG.md
- pysat/tests/classes/cls_instrument_library.py
Addresses #1059
Uses the hidden `_set_data_dirs` method to set the temporary directory in the inheritable unit tests.  This allows the path to be set without writing to file, which will break a user's local setup until the tests restore the original path at the end.
The fix here will be inherited for tests in other packages.
- Open the pysat_settings.json file in a text editor that updates live
- Run unit tests for a penumbra package (eg, pysatNASA)
- Look for data_dirs parameter to change …
> BUG: use of temporary directory in test package

- .github/workflows/main.yml
Looking over the logs, this is working as expected.
My thought on the netcdf4 install earlier was wrong.  Looks like the older version installs correctly after the latest fails.
Pandas has updated a new version (1.5.2) which fixes the nep29 issues, correctly installs an older version for the operational version.
> STY: Clean up manual installs

- CHANGELOG.md
- pysat/_instrument.py
- pysat/tests/classes/cls_instrument_access.py
Addresses #1058
Slicing by name is a pandas feature that pysat passes through.  Since this doesn't work for xarray, this clarifies the docstrings.
Also expands the testing to validate that pandas functionality is there.
```
inst = pysat.Instrument("pysat", "testing")
inst.load(2009, 2)
inst[inst.index[0]:inst.index[10], 'uts':'slt']
```
* Operating system: Monterrey 12.6.1
> BUG: data access

- CHANGELOG.md
- docs/citing.rst
- docs/tutorial/tutorial_basics.rst
- pysat/_instrument.py
- pysat/tests/classes/cls_instrument_access.py
- pysat/tests/test_instrument.py
Addresses #988
When setting a single value, xarray broadcasts data unneccessarily. This maps a single value to coords.
**EDIT: If the variable is new, it will still broadcast over time and warn the user.**
Loading an xarray object and assigning it a new variable.
* Operating system: Monterrey 12.6.1
> BUG: xarray coords

- pysat/_instrument.py
- pysat/tests/classes/cls_instrument_property.py
Addresses #1022
Allows default `start` and `stop` times to be set for libraries.
Can test against: https://github.com/pysat/pysatMadrigal/pull/82
Alternatively,
```
import functools
import pysat
from pysat.instruments.methods import testing as ps_meth
inst = pysat.Instrument('pysat', 'testing')
inst.remote_file_list()
inst._list_remote_files_rtn = functools.partial(
ps_meth.list_remote_files, 
start=dt.datetime(2018, 1, 1), stop=dt.datetime(2018, 12, 31))
inst.remote_file_list()
```
The first instance should yield dates between 2008 and 2010. After attaching a new routine with different default start and stop dates, the new date range (2018) is retrieved. When on `develop`, the 2nd instance will fail.
**Test …
> BUG: check for user-supplied kwargs in list_remote_files

- CHANGELOG.md
- pysat/_instrument.py
- pysat/tests/test_instrument.py
- pysat/utils/_core.py
When loading data that has an xarray format, it is possible to downselect data to a non-existent time range, but still have data that doesn't depend on time in the other dimensions.  In this case, because there's data, `instrument.empty` will be False.  However, there are no index values to select.  This causes pysat to Error.
```
import pysat
guvi = pysat.Instrument(inst_module=pysatNASA.instruments.timed_guvi, tag='sdr-imaging', inst_id='low_res'
stime = pysatNASA.instruments.timed_guvi._test_dates[guvi.inst_id][guvi.tag]
guvi.download(start=stime)
guvi.load(date=stime, use_header=True)
```
This will error on a different branch, but work with this one.
**Test …
> BUG: empty evaluation doesn't work with xarray

- CHANGELOG.md
- pysat/_instrument.py
The current output of kwargs can be difficult to read, especially when multiple kwargs which include lengthy strings are used.  This makes it particularly difficult when comparing multiple instruments with different TLEs when using pysatMissions.
This parses each kwarg as a separate line when running `print(inst)`.
```
import pandas as pds
import pysat
from pysatMissions.instruments import missions_sgp4
line1 = '1 55129U 98067UW  23039.82653086  .00049915  00000-0  78305-3 0  9991'
line2 = '2 55129  51.6397 243.8305 0001856 340.7022  19.3898 15.53177014  6499'
file_date_range = pds.date_range(dt.datetime(2022, 12, 30),
dt.datetime(2023, 2, 28))
sport = pysat.Instrument(inst_module=missions_sgp4, …
```
> ENH: kwarg format for `print(inst)`

- CHANGELOG.md
- pysat/instruments/methods/testing.py
- pysat/instruments/pysat_ndtesting.py
- pysat/instruments/pysat_testing.py
- pysat/instruments/pysat_testing2d.py
- pysat/instruments/pysat_testing_xarray.py
- pysat/tests/test_instrument_index.py
Addresses #1094
Deprecates `malformed_index` for test instruments.  This is replaced by `non_monotonic_index` and `non_unique_index`, allowing these two functions to be changed independently.
```
import pysat
inst = pysat.Instrument('pysat', 'testing', non_monotonic_index=True)
```
etc.
* Version number: Python 3.10.8
> DEP/STY: Deprecate `malformed_index`, add `non_unique_index` kwargs

- CHANGELOG.md
- pysat/_instrument.py
- pysat/tests/test_instrument.py
#1074 is out of date with other pulls approved.  This should fix the issue noted.  Adds a test in the xarray tests.
```
import pysat
inst = pysat.Instrument('pysat', 'ndtesting', use_header=True)
inst['new_val'] = ('time', np.ones(864))
```
This fails in develop, but succeeds here.
* Version number: Python 3.10.8
> BUG: xarray and tuple

- CHANGELOG.md
- pysat/tests/test_utils_io.py
- pysat/utils/io.py
Addresses #923 & #1098
Adds quality of life kwargs to `utils.io.load_netcdf` for xarray datasets. Both required for upcoming pysatNASA pulls. Defaults to existing behavior.
- `combine_by_coords` allows users to specify use a nested combining multi-day datasets when coords are not set in the data files.
- `strict_dim_check` suppresses the warning message if the epoch is not listed in dims
Tested against loading multiple days of GOLD instruments.
```
import pysat
gold = pysat.Instrument(platform='ses14', name='gold', tag='tlimb')
d0 = dt.datetime(2019, 9, 5)
dn = dt.datetime(2019, 9, 7)
gold.load(date=d0, end_date=dn)
```
* Operating system: Mac Monterrey
* Version number: Python …
> ENH: xarray io kwargs: `combine_by_coords` and `strict_dim_check`

- CHANGELOG.md
- pysat/instruments/pysat_testing.py
- pysat/tests/test_utils.py
- pysat/utils/_core.py
Addresses #1097
When generating a list of tests to run for multiple load options, the list is incorrectly set because elements are rewritten.  This attaches copies of the objects to the list of test cases so that the elements are not rewritten.
Pick an instrument in a supporting package (ie, timed_guvi).  Add multiple load options.
```
_test_load_opt = {iid: {tag: [{'combine_times': True}, {'combine_times': False}]
for tag in inst_ids[iid]} for iid in ['high_res',
'low_res']}
```
Now generate the instrument tests.
```
from pysat.tests.classes import cls_instrument_library as clslib
instruments = clslib.InstLibTests.initialize_test_package(
clslib.InstLibTests, inst_loc=pysatNASA.instruments)
```
Inspecting the tests for …
> BUG: support for multiple load options

- CHANGELOG.md
- pysat/_instrument.py
- pysat/_meta.py
- pysat/instruments/methods/testing.py
- pysat/instruments/pysat_netcdf.py
- pysat/tests/test_instrument.py
- pysat/tests/test_meta.py
- pysat/tests/test_utils.py
- pysat/tests/test_utils_files.py
- pysat/tests/test_utils_io.py
- pysat/utils/__init__.py
- pysat/utils/_core.py
- pysat/utils/files.py
- pysat/utils/io.py
Potentially addresses #707 by adding a core utility to consistently update fill values in the metadata and data simultaneously.  Also fixes issues found when testing that this worked as desired when printing netCDF files.
```
import pysat
inst = pysat.Instrument('pysat', 'testing', use_header=True)
print(inst.meta['mlt', inst.meta.labels.fill_val])  # Should be np.nan
pysat.utils.update_fill_values(inst, 'mlt', -1.0)
print(inst.meta['mlt', inst.meta.labels.fill_val])  # Should be -1.0
```
* Any details about your local setup that …
> ENH/BUG: added a function to update fill values

- CHANGELOG.md
- pysat/tests/classes/cls_instrument_library.py
Addresses #974 (partial)
pysatNASA is seeing fails to properly clean up the temporary directory on windows: https://github.com/pysat/pysatNASA/pull/159
This is only happening for this pull, but it happens consistently.  It could just be we've hit a critical mass of instruments with the latest additions.
Fix based on the one implemented in test_utils_io.
this needs a version at test pypi to properly test, or a modified github actions job to install from this branch.
* Operating system: ???
* Version number: Python 3.10 …
> BUG: windows `tempdir` cleanup

- CHANGELOG.md
- pysat/_constellation.py
- pysat/constellations/__init__.py
- pysat/constellations/single_test.py
- pysat/constellations/testing.py
- pysat/constellations/testing_partial.py
- pysat/instruments/pysat_testing.py
- pysat/tests/test_constellation.py
Addresses #798
Adds a partially empty constellation object for testing and uses this in the existing tests for a partially loaded constellation.
- Fixed a bug where `_index` attempts to construct the index from empty instruments
- Set the `instruments.pysat_testing` tag='no_download' to return an empty pandas DataFrame for `load`
- Added `constellations.testing_partial`, which loads a partially empty constellation dataset
- Reduced default num_samples for constellation test objects
- Removed deprecated instruments from constellation test objects
```
import pysat
from pysat import constellations
const = pysat.Constellation(const_module=constellations.testing_partial, use_header=True)
const.load(2009, 1)
```
`const[0]` returns …
> ENH/TST: add partially empty constellation

- pysat/_instrument.py
Addresses #1109
Updates meta data type after load is run. If instruments have clean or preprocess routines that modify data, the data type needs to exist in `inst.meta._data_types` before it is modified by `setitem`.
running pytest on various pysat library packages
* Version number: Python 3.10.8
Packages tested
> BUG: fix meta type before preprocess / clean

- CHANGELOG.md
- pysat/_instrument.py
- pysat/tests/classes/cls_instrument_access.py
Addresses bug found and temporarily fixed in https://github.com/pysat/pysatSpaceWeather/issues/117, where loading data with a pad for a period where no data is available now causes an error when trying to slice the index.
Added a new unit test.  Couldn't get the error locally, but it's showing up here: https://github.com/pysat/pysatSpaceWeather/pull/116
* Operating system: GitHub Actions
* Version number: Python 3.6-3.10
> Range index error

- CHANGELOG.md
- pysat/instruments/pysat_testmodel.py
- pysat/tests/classes/cls_instrument_library.py
- pysat/utils/io.py
Preparation for #585
Bugs fixed:
- Mismatch between meta and data in `pysat_testmodel`.  Meta values without data will not be written to file.
- Bad check for empty meta value (detailed in #585)
- Renaming 'time' as 'time' prompts an xarray warning, now checks that epoch name is not 'time'
writing a netcdf from the test instruments.  A mismatch between meta and data will result in values being dropped.
> BUG: fix meta values in test instruments

- CHANGELOG.md
- docs/new_instrument.rst
- pysat/instruments/methods/testing.py
- pysat/tests/classes/cls_instrument_library.py
- pysat/tests/test_instruments.py
Addresses #1009 by adding a general test triggered by an optional testing variable to the standard set of Instrument tests.  Adapted the clean method in the test instruments to run all potential iterations of the allowed behaviour, which includes:
- logging messages
- warnings
- errors
- changing the clean level
Updated the documentation to describe how this testing should be done.
Added unit tests.  Also added this line to `ace_epam.py` in pysatSpaceWeather and ran the local unit tests.
```
_clean_warn = {'': {'': {'dusty': [('logger', 'WARN',
"unused clean level 'dusty', reverting to 'clean'",
'clean')]}}}
```
* …
> TST: Clean warnings

- CHANGELOG.md
- pysat/_instrument.py
- pysat/tests/classes/cls_instrument_property.py
Sometimes a valid tag is used, but with the wrong inst_id.  The current ValueError message just tells you that you have a bad tag.  The new ValueError message tells you that you have a bad tag for the inst_id you used, and provides a list of the valid combinations.
```
import pysat
guvi = pysat.Instrument(inst_module=pysatNASA.instruments.timed_guvi, tag='sdr-imaging')
```
This will fail with a ValueError.  The old error reads: `ValueError: 'sdr-imaging' is not one of the supported tags for inst ID ['']. Supported ['edr-aur']`, the new error will be more informative about what you need to do to fix the call.
* Version …
> Improved Instrument ValueError message for a bad tag

- CHANGELOG.md
- pysat/_instrument.py
- pysat/tests/classes/cls_instrument_access.py
Addresses #1137 by adding an `include` kwarg to `concat_data` that allows the current `self.data` object to be inserted into the desired concatenated data list at any location.  This allows `load` to call `concat_data` once instead of twice.
Added a unit test parametrization that uses `include` to mimic the behaviour of `prepend`.
> ENH: added `include` kwarg to `concat_data`

- CHANGELOG.md
- pyproject.toml
- requirements.txt
- test_requirements.txt
Addresses #1119 and #1142
`sphinx` 7.0+ dropped a style tag that `sphinx_rtd_theme` relied on. The latest version fixed this, so there's no need for us to maintain a cap.
pandas 2.1.1 is less memory efficient, and crashes the tests on GitHUb Actions (though not locally on my machine). This adds a cap (temporarily?) so that CI can continue.
running sphinx-build
> BUG: sphinx and pandas caps

- CHANGELOG.md
- pysat/_files.py
- pysat/_instrument.py
- pysat/utils/registry.py
Addresses #1133, #1135
Allows the `overwrite` kwarg to be passed through `registration_by_module`
Also updates some docstrings to point to the correct location of functions that moved to `pysat.utils.files`.
Via github actions
> ENH: overwrite kwarg for `registration_by_module`

- CHANGELOG.md
- docs/tutorial/tutorial_basics.rst
- pysat/_instrument.py
- pysat/constellations/testing.py
- pysat/constellations/testing_partial.py
- pysat/tests/classes/cls_instrument_access.py
- pysat/tests/classes/cls_instrument_library.py
- pysat/tests/classes/cls_instrument_property.py
- pysat/tests/test_constellation.py
- pysat/tests/test_files.py
- pysat/tests/test_instrument.py
- pysat/tests/test_instrument_custom.py
- pysat/tests/test_instrument_index.py
- pysat/tests/test_instrument_padding.py
- pysat/tests/test_instruments.py
- pysat/tests/test_meta.py
- pysat/tests/test_methods_general.py
- pysat/tests/test_methods_testing.py
- pysat/tests/test_orbits.py
- pysat/tests/test_utils.py
- pysat/tests/test_utils_coords.py
- pysat/tests/test_utils_files.py
- pysat/tests/test_utils_io.py
Partially addresses #1020 by removing `use_header` as a standard kwarg from `Instrument.load`.  Updated the DeprecationWarning and removed unnecessary use of `use_header` from the test suite.
```
import pysat
inst = pysat.Instrument('pysat', 'testing')
inst.load(2009, 2, use_header=True)
inst.load(2009, 1, use_header=False)
``` …
> MAINT: Update `use_header` handling

- pysat/_instrument.py
- pysat/instruments/methods/general.py
- pysat/tests/classes/cls_instrument_library.py
- pysat/tests/test_methods_general.py
Addresses https://github.com/pysat/pysatSpaceWeather/issues/127.
```
import pysat
import pysatSpaceWeather
f107 = pysat.Instrument('sw', 'f107', tag='daily', pad=dt.timedelta(days=1))
f107.download(start=f107.today())
f107.load(date=f107.today())
f107.pad = None
f107.load(date=f107.today())
```
> Padding bugfix

- CHANGELOG.md
- docs/new_instrument.rst
- pysat/instruments/pysat_ndtesting.py
- pysat/instruments/pysat_testing.py
- pysat/tests/classes/cls_instrument_library.py
Addresses #1120 by improving the pysat_testing.py load logic.  Also added a new unit test and expanded the 'no_download' tests to encompass xarray.
- Potentially breaking change: tests enforce an expected output for empty data
Added new unit tests
> TST: test empty load output

- .github/workflows/main.yml
- CHANGELOG.md
- pysat/tests/test_files.py
- pysat/tests/test_utils.py
Addresses #871
Tidies up issues regarding network lock tests.
- Remove todo
- use temporary directory for files created
via pytest
* Operating system: Ventura
> TST: network lock cleanup

- CHANGELOG.md
- pysat/tests/test_utils_files.py
- pysat/utils/files.py
Addresses #854 by adding unit tests for all the file utility functions instead of relying solely on integration tests.
Ran unit tests
> TST: added more file utility unit tests

- CHANGELOG.md
- pyproject.toml
- pysat/tests/classes/cls_instrument_library.py
- test_requirements.txt
The instrument tests only teardown at the class level, not method level. Adds a `teardown_method` to delete any loaded instruments and reference dates, if present. This clears up the system memory for when large instrument libraries (like pysatNASA) are loaded. If sufficiently large, the pytest job may be killed unexpectedly.
Tested against pysatNASA. Tests will fail partway through `test_load_multiple_days` in develop, but all tests run here.
* Operating system: Ventura …
> TST: teardown method

- CHANGELOG.md
- docs/conf.py
- pysat/__init__.py
- pysat/instruments/methods/__init__.py
- pysat/instruments/methods/general.py
- pysat/instruments/pysat_netcdf.py
- pysat/tests/classes/cls_instrument_integration.py
- pysat/tests/classes/cls_registration.py
- pysat/tests/test_files.py
- pysat/tests/test_instrument.py
- pysat/tests/test_instrument_index.py
- pysat/tests/test_instrument_padding.py
- pysat/tests/test_instruments.py
- pysat/tests/test_methods_general.py
- pysat/tests/test_methods_testing.py
- pysat/tests/test_utils.py
- pysat/tests/test_utils_io.py
- pysat/tests/test_utils_testing.py
- pysat/utils/__init__.py
- pysat/utils/_core.py
- pysat/utils/registry.py
- setup.cfg
There's a new version of flake8! Two major changes that I can tell:
- Specifying specific errors to ignore for files in setup.cfg no longer works (see error [here](https://github.com/pysat/pysat/actions/runs/7266126170/job/19797227294))
- A number of additional flake8 errors are popping up (mostly unused imports, this may have slipped under the radar due to changes in how setup.cfg was processed with flake8 6.0)
This updates the issues throughout the code. Major changes include
- Adding comments for `pysat/__init__` to explain why imports and code are mixed, including updating the logical flow a bit
- The file-level ignore statements have been moved to the files as line-level noqa statements (as is the standard elsewhere in the code)
- Most of the "unused imports" that are removed are …
> MAINT: flake8 updates

- CHANGELOG.md
- docs/new_instrument.rst
- pyproject.toml
- pysat/_instrument.py
- pysat/tests/classes/cls_instrument_library.py
- pysat/utils/_core.py
Many of the files across the ecosystem require significant updates to run the new tests. This adds a new testing flag, specifically for `test_load_multiple_days` and `test_load_w_pad`. By default, this is set to `True`, but instruments may set it to `False` for known failures that are documented in the issues. This allows the testing suite to run while instrument modules are updated. TODO statements are tied to the next version release. 
Down the line, this could be used for other new standard instrument tests that require significant upgrades throughout the ecosystem.
pytest on the `pysatNASA` branch [here](https://github.com/pysat/pysatNASA/pull/223)
pytest on the `pysatModels` …
> ENH: add `_new_tests` to allow instruments to temporarily ignore tests requiring concat

- .github/workflows/docs.yml
- .github/workflows/main.yml
- .github/workflows/pip_rc_install.yml
- .github/workflows/stats.yml
- CHANGELOG.md
- README.md
- pyproject.toml
- requirements.txt
Closes #1142 
Pandas has released updates that runs again on github actions. 
- Removes the cap
- Updates versions for github actions to remain compliant
- Updates NEP29 minimum versions to test.
via github actions
- [rc] Make sure you are merging into the ``develop`` (not ``main``) branch
> MAINT: github actions, remove pandas cap, update NEP29

- CHANGELOG.md
- pysat/tests/classes/cls_instrument_library.py
- pysat/tests/test_utils_files.py
- pysat/tests/test_utils_io.py
- pysat/utils/files.py
Addresses #1173 by introducing consideration of supplied type when parsing filename formats.
Ran using a modified example from the test case: 
```
import pysat
files = ["jro20230417drifts.001.hdf5”, “jro20230417drifts.txt.hdf5"]
format_str = "jro{year:04d}{month:02d}{day:02d}drifts.{version:03d}.hdf5"
pysat.utils.files.parse_fixed_width_filenames(files, format_str)
```
The output should not have the second file in `files` as a viable output file.
* Operating system: OS X. Big Sur
- …
> ENH/BUG: Filename fix for #1173

- pyproject.toml
- pysat/tests/classes/cls_instrument_library.py
- pysat/utils/time.py
- test_requirements.txt
Not all the testing suite methods clean up after themselves. Found during troubleshooting for pysatCDAAC.
Other minor tweaks to get check marks up and running:
- Version cap for pysatSpaceWeather. The 0.1.0 release is breaking tests for mac. This is only used to support certain tests. Since this is on the scope to remove as a dependency when new functions are added (#779), version cap is the path forward.
- Moved a link to comments to satisfy the Sphinx. 🦁 
running against pysatMissions.
* Operating system: Ventura 13.6.2
- [rc] Make sure you are merging into the ``develop`` (not ``main``) branch
If this is a release PR, …
> MAINT: tidy tests

- CHANGELOG.md
- docs/examples/example_orbit.rst
- pysat/_constellation.py
- pysat/_instrument.py
- pysat/_orbits.py
- pysat/instruments/methods/testing.py
- pysat/instruments/pysat_ndtesting.py
- pysat/instruments/pysat_testing.py
- pysat/instruments/pysat_testmodel.py
- pysat/tests/classes/cls_instrument_access.py
- pysat/tests/classes/cls_instrument_iteration.py
- pysat/tests/classes/cls_instrument_library.py
- pysat/tests/classes/cls_instrument_property.py
- pysat/tests/test_constellation.py
- pysat/tests/test_instrument.py
- pysat/tests/test_instrument_padding.py
- pysat/tests/test_instruments.py
- pysat/tests/test_methods_testing.py
- pysat/tests/test_utils.py
- pysat/tests/test_utils_coords.py
- pysat/tests/test_utils_io.py
- pysat/tests/test_utils_time.py
- pysat/utils/coords.py
- pysat/utils/io.py
- pysat/utils/time.py
Addresses #1186, #1185, #1189
- Update usage of `dims` to be consistent with future versions of `xarray`
- Update frequency strings for `pandas`
- Update usage of getitem for `pds.Series` (ie, `.iloc` for integer indices)
- Updates usage of `dt.datetime.utcnow()` to `dt.datetime.now(dt.timezone.utc)`
via pytest and inspection of warnings.
* Operating system: Ventura 13.6.4
* Version number: Python 3.11.5
* pandas 2.2.0 and pandas 1.5.3
> MAINT: FutureWarnings for datetime, pandas, xarray

- .github/workflows/main.yml
- CHANGELOG.md
- pyproject.toml
Happy Deprecation Day (observed)! 
Updates the GitHub Actions main workflow to drop tests for Python 3.9. Python 3.10 is now the minimum tested version. NEP29 recommends dropping support as of Apr 5, 2024.
https://numpy.org/neps/nep-0029-deprecation_policy.html
via GitHub Actions
> MAINT: NEP29 updates

- .zenodo.json
- CHANGELOG.md
- pysat/_instrument.py
Addresses #1198 
Frequency-based iteration was failing for files with irregular frequencies, particularly with frequencies of less than one day. 
This pull imposes a minimum frequency of 1D. Once the file frequency is calculated, if it is less than 1D, it is set to 1D.
pysatCDAAC unit tests run locally with patch-develop branch rc on TestPyPI as pysat version
Test Configuration:
Operating system: MacOS 14.5
Version number: Python 3.10
> Impose minimum frequency of 1D

- CHANGELOG.md
- pysat/tests/classes/cls_instrument_library.py
Addresses #1196
Only tests for clean warning if a particular inst_id / tag combo exists in the instrument module. Defaults to skip test if this is not present.
Run pytest for pysatNASA.
* Operating system: Mac 14.5
> BUG: Assumptions in clean tests

- CHANGELOG.md
- pysat/_instrument.py
Addresses #1201 
Updates docstring for `export_pysat_info` instructions, including potential use cases for the non-default case.
inspection of docs
GitHub Actions workflows (ignoring known issues with python 3.6.8)
> BUG/DOC: export pysat info

- .github/workflows/main.yml
- .github/workflows/pip_rc_install.yml
- CHANGELOG.md
- pyproject.toml
Implements SPEC-0000 test requirements instead of limiting to only numpy (NEP29). Uses two-year support window to test for earlier versions of 
- pandas
- scipy
- xarray
See https://scientific-python.org/specs/spec-0000/
Also adds minimum versions for these in pyproject.toml to match the current tests in the operational environment.
via github actions, including verifying that correct versions were installed for this job.
- [na] Make sure you are merging into the ``develop`` (not ``main``) branch
> MAINT: SPEC-0000 tests

- .gitignore
- CHANGELOG.md
- MANIFEST.in
Addresses #TBD
PyHC is testing out a common unit-test environment for core packages. This is currently accomplished by running the unit tests for a pip-installed version of pysat. While the tests are included as core code for use throughout the ecosystem, the test data some of the pysat-unique tests requires are not included here. This updates the manifest so that these files are included.
- Created a clean virtual environment.
- Created tar.gz via `python -m build --sdist`
- Installed via pip in clean env directly from the tar.gz => `pip install '../code/core/pysat/dist/pysat-3.2.2rc0.tar.gz[test]'`
- Ran tests via `pytest --pyargs pysat.tests`
* Operating system: Sonoma 14.7.1
* Version number: Python 3.12
* …
> BUG: include test data in MANIFEST

- .github/workflows/main.yml
- .github/workflows/pip_rc_install.yml
- .gitignore
- CHANGELOG.md
- README.md
- pyproject.toml
- pysat/__init__.py
- pysat/tests/classes/cls_instrument_library.py
- pysat/utils/_core.py
- Updates the operational tests for the new configuration (python 3.9, numpy 1.23.5). 
- Sets python 3.9 as the new minimum supported version
- Removes some code designed to interface purely for python 3.6
- Updates .gitignore to play nicely with pyenv-virtualenv
Via GitHub Actions, including the pip rc install workflow.
- [rc] Make sure you are merging into the ``develop`` (not ``main``) branch
> MAINT: ops for python 3.9
